[package]
name = "masterdata-command"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
native-consumer = ["masterdata-engine/native-consumer"]

[[bin]]
name = "masterdata"
path = "src/main.rs"

[dependencies]
masterdata-engine = { path = "../engine" }
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
