import {invoke} from "@tauri-apps/api/core";
import {desktop} from "./workspace";
const SOURCE="sources/catalog-data.yaml",SCHEMA="sources/catalog-schema.yaml";
const frame=()=>new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));
async function until(test:()=>boolean,message:string){const deadline=performance.now()+10000;while(!test()){if(performance.now()>deadline)throw new Error(message);await frame();}}
function assert(test:unknown,message:string):asserts test{if(!test)throw new Error(message);}
const shown=(e:HTMLElement)=>!!e.getClientRects().length&&getComputedStyle(e).visibility!=="hidden"&&!e.closest('[aria-hidden="true"]')&&(!e.closest('.ant-drawer')||!!e.closest('.ant-drawer-open'));
function activeButtons(){const overlay=[...document.querySelectorAll<HTMLElement>('.ant-modal-wrap')].find(shown)??document.querySelector<HTMLElement>('.ant-drawer-open');return [...(overlay??document).querySelectorAll<HTMLButtonElement>('button')];}
function button(label:string){const e=activeButtons().find(e=>shown(e)&&(e.getAttribute('aria-label')===label||e.textContent===label));assert(e,`missing ${label}`);return e;}
async function click(label:string){await until(()=>activeButtons().some(e=>shown(e)&&!e.disabled&&(e.getAttribute('aria-label')===label||e.textContent===label)),`action not ready: ${label}`);button(label).click();await frame();}
function input(label:string){const e=[...document.querySelectorAll<HTMLInputElement>('input')].find(e=>shown(e)&&e.getAttribute('aria-label')===label);assert(e,`missing ${label}`);return e;}
function text(e:HTMLInputElement,value:string){Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(e,value);e.dispatchEvent(new Event('input',{bubbles:true}));}
function key(e:HTMLElement,key:string,extra:KeyboardEventInit={}){e.dispatchEvent(new KeyboardEvent('keydown',{key,keyCode:key==='ArrowDown'?40:key==='Enter'?13:undefined,which:key==='ArrowDown'?40:key==='Enter'?13:undefined,bubbles:true,...extra}));}
async function tab(label:string){await until(()=>[...document.querySelectorAll<HTMLElement>('[role="tab"]')].some(e=>shown(e)&&e.textContent===label),`missing tab ${label}`);const e=[...document.querySelectorAll<HTMLElement>('[role="tab"]')].find(e=>shown(e)&&e.textContent===label)!;e.click();await frame();}
async function choose(label:string,option:string){const e=input(label);e.focus();key(e,'ArrowDown');await until(()=>[...document.querySelectorAll<HTMLElement>('.ant-select-item-option-content')].some(e=>shown(e)&&e.textContent===option),`missing option ${option}`);[...document.querySelectorAll<HTMLElement>('.ant-select-item-option-content')].find(e=>shown(e)&&e.textContent===option)!.click();key(e,'Escape');await frame();}
async function open(){button("テーブルの操作").click();await until(()=>[...document.querySelectorAll<HTMLElement>('[role="menuitem"]')].some(e=>shown(e)&&e.textContent==="テーブルの詳細…"),'Table detail menu missing');[...document.querySelectorAll<HTMLElement>('[role="menuitem"]')].find(e=>shown(e)&&e.textContent==="テーブルの詳細…")!.click();await until(()=>!!document.querySelector('.table-declarations .ant-table'),'saved declaration detail missing');}
async function review(){await until(()=>[...document.querySelectorAll<HTMLButtonElement>('button')].some(e=>shown(e)&&e.textContent==="変更を確認"&&!e.disabled),'Review action not ready');button("変更を確認").click();await until(()=>!!document.querySelector("[aria-label=\"テーブル宣言の変更計画\"]")&&!button("適用").disabled,'declaration Plan not ready');}
async function apply(){await click("適用");await until(()=>![...document.querySelectorAll<HTMLElement>("[aria-label=\"テーブル宣言の変更計画\"]")].some(shown)&&!!document.querySelector('.table-declarations .ant-table'),'declaration commit did not return to detail');await frame();}
async function close(){button("閉じる").click();await until(()=>!document.querySelector('.ant-drawer-open .table-declarations'),'detail did not close');await until(()=>document.activeElement?.getAttribute('aria-label')==="テーブルの操作",'detail Close lost keyboard action focus');}
export async function run({startup}:{startup:Record<string,unknown>}) {
 const checks:string[]=[];
 try {
  await until(()=>!!desktop.surface.inventory&&document.hasFocus(),'native Project not ready');await desktop.selectTarget(SOURCE,'declaration-setup',false);
  const row=desktop.surface.projection!.rows[0].id,originalIds=desktop.surface.projection!.rows.map(r=>r.id),top=desktop.viewport!.getBoundingClientRect().top;
  desktop.viewport!.scrollLeft=11*160;
  await until(()=>!!desktop.viewport!.querySelector(`[data-row="${CSS.escape(row)}"] [data-column="11"]`),'scrolled name cell did not become visible');
  const cell=desktop.viewport!.querySelector<HTMLElement>(`[data-row="${CSS.escape(row)}"] [data-column="11"]`);assert(cell,'name cell missing');
  const rect=cell.getBoundingClientRect(),pointer={bubbles:true,button:0,pointerId:1,pointerType:'mouse',isPrimary:true,clientX:rect.left+rect.width/2,clientY:rect.top+rect.height/2};
  cell.dispatchEvent(new PointerEvent('pointerdown',{...pointer,buttons:1}));document.dispatchEvent(new PointerEvent('pointerup',{...pointer,buttons:0}));
  await until(()=>desktop.viewport!.getAttribute('aria-activedescendant')===cell.id,'name cell selection missing');cell.dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));
  await until(()=>!!document.querySelector('.active-cell-editor input'),'scalar editor missing');const editor=document.querySelector<HTMLInputElement>('.active-cell-editor input')!;assert(editor.value==='Debug Sword','scalar editor opened another cell');text(editor,'Held declaration draft');key(editor,'Enter');await until(()=>desktop.surface.status.dirty.includes(SOURCE)&&!desktop.interaction.editor,'draft commit missing');
  await open();await close();assert(desktop.surface.status.dirty.join(',')===SOURCE,'opening detail dirtied a source');checks.push('open-close-physical-draft-focus');
  await open();button('編集: id MessagePackキー').click();await until(()=>!!document.querySelector("input[aria-label=\"MessagePackキー\"]"),'key editor missing');text(input("MessagePackキー"),'25');key(input("MessagePackキー"),'Enter',{isComposing:true});await frame();assert(!document.querySelector("[aria-label=\"テーブル宣言の変更計画\"]"),'composition Enter reviewed a structural change');
  await review();assert(document.querySelector("[aria-label=\"テーブル宣言の変更計画\"]")!.textContent?.includes('キー 0 → 25'),'Plan omitted key before/after');button("比較").click();await until(()=>!!desktop.surface.comparison,'Plan Compare missing');assert(desktop.surface.comparison!.before.includes('key: 0')&&desktop.surface.comparison!.after.includes('key: 25'),'Compare omitted exact candidate');button("閉じる").click();await until(()=>!!document.querySelector(".ant-drawer-open [aria-label=\"テーブル宣言の変更計画\"]"),'Compare did not return to Plan');await apply();checks.push('messagepack-review-compare-composition');
  await tab("キー");await click("主キーを編集");key(input('キーのフィールド'),'Backspace');await frame();await choose('キーのフィールド','intValue');await review();await apply();await tab("キー");assert(document.querySelector('.table-declarations')!.textContent!.includes('intValue · 一意'),'Primary Key edit missing');
  await tab("キー");await click("主キーを編集");key(input('キーのフィールド'),'Backspace');await frame();await choose('キーのフィールド','id');await review();await apply();checks.push('primary-key-direct-ordered-components');
  await tab("キー");await click('副キーを編集: 3');key(input('キーのフィールド'),'Backspace');await frame();key(input('キーのフィールド'),'Backspace');await frame();await choose('キーのフィールド','rarity');await choose('キーのフィールド','code');await review();await apply();await tab("キー");assert(document.querySelector('.table-declarations')!.textContent!.includes('rarity → code · 一意'),'composite order not committed');checks.push('secondary-key-composite-order');
  await tab("キー");await click("キーを追加");await choose('キーのフィールド','name');const checkbox=[...document.querySelectorAll<HTMLLabelElement>('label')].find(e=>shown(e)&&e.textContent==="重複を許可");assert(checkbox,'Nonunique control missing');checkbox.click();await review();await apply();
  await tab("参照");await click("参照を追加");text(input("参照名"),'peers');await choose('参照元のフィールド','name');await choose("参照先のテーブル",'item');await choose("参照先のキー",'name · 重複許可');await review();
  const plan=document.querySelector("[aria-label=\"テーブル宣言の変更計画\"]")!.textContent!;assert(plan.includes('GetPeers')&&plan.includes('複数')&&plan.includes("必須"),'Rust resolved Reference feedback missing');await apply();checks.push('reference-add-rust-resolved-feedback');
  await tab("参照");await click('編集: peers 参照');assert(input("参照ヘルパー名の指定").value==='','default helper became an explicit override');text(input("参照ヘルパー名の指定"),'FindPeers');await review();await apply();checks.push('reference-helper-override');
  await tab("キー");await click('副キーを削除: 4');button("変更を確認").click();await until(()=>!!document.querySelector('.table-declarations .ant-alert-error'),'dependent key removal not rejected');assert(!document.querySelector("[aria-label=\"テーブル宣言の変更計画\"]"),'unsafe key removal produced a Plan');button("詳細に戻る").click();checks.push('incoming-reference-key-removal-rejected');
  await tab("参照");button('削除: peers 参照').click();await until(()=>document.activeElement?.getAttribute('aria-label')==="テーブル宣言の変更を確認",'removal input lost keyboard action focus');await review();await click("適用");await until(()=>!!desktop.surface.choice&&[...document.querySelectorAll<HTMLButtonElement>('button')].some(e=>shown(e)&&e.textContent==="キャンセル"),'destructive guard missing');assert(desktop.surface.choice!.description.includes('peers'),'confirmation omitted the captured removal target');button("キャンセル").click();await until(()=>!!document.querySelector(".ant-drawer-open [aria-label=\"テーブル宣言の変更計画\"]")&&document.activeElement?.getAttribute('aria-label')==="テーブル宣言の変更計画",'Cancel dropped the reviewed Plan or its focus');assert(document.querySelector("[aria-label=\"テーブル宣言の変更計画\"]")!.textContent!.includes('削除: peers'),'Cancel dropped removal understanding');
  await click("適用");await until(()=>!!desktop.surface.choice&&[...document.querySelectorAll<HTMLButtonElement>('button')].some(e=>shown(e)&&e.textContent==="削除"),'destructive authorization missing');button("削除").click();await until(()=>!document.querySelector("[aria-label=\"テーブル宣言の変更計画\"]")&&!!document.querySelector('.table-declarations .ant-table'),'authorized removal failed');await tab("参照");assert(!document.querySelector('.table-declarations')!.textContent!.includes('FindPeers'),'authorized Reference removal not reflected');checks.push('reference-remove-explicit-authorization');
  await tab("キー");button('副キーを削除: 4').click();await review();await click("適用");await until(()=>!!desktop.surface.choice&&[...document.querySelectorAll<HTMLButtonElement>('button')].some(e=>shown(e)&&e.textContent==="削除"),'Key destructive authorization missing');button("削除").click();await until(()=>!document.querySelector("[aria-label=\"テーブル宣言の変更計画\"]")&&!!document.querySelector('.table-declarations .ant-table'),'Key removal failed');await tab("キー");assert(!document.querySelector('.table-declarations')!.textContent!.includes('name · 重複許可'),'Key removal not reflected');
  await tab("MessagePackキー");await click('編集: id MessagePackキー');text(input("MessagePackキー"),'26');await review();await invoke('evidence_write',{report:{phase:'declaration-stale'}});
  await until(()=>button("適用").disabled&&[...document.querySelectorAll<HTMLButtonElement>('button')].some(e=>shown(e)&&e.textContent==="テーブルの詳細を再取得"),'external change left old Plan enabled');assert(desktop.surface.projection!.columns[0].field.key===25,'stale Plan auto-applied');await click("テーブルの詳細を再取得");await until(()=>!document.querySelector("[aria-label=\"テーブル宣言の変更計画\"]")&&!!document.querySelector('.table-declarations .ant-table'),'explicit detail refresh failed');checks.push('stale-plan-no-auto-replan-apply');
  await click('編集: id MessagePackキー');text(input("MessagePackキー"),'26');await review();await invoke('evidence_bad_migration_reply');await click("適用");await until(()=>!!desktop.surface.uncertainField&&[...document.querySelectorAll<HTMLButtonElement>('button')].some(e=>shown(e)&&e.textContent==="現在のソース一式を再確認"),'lost commit reply did not enter Unknown');
  assert(![...document.querySelectorAll<HTMLButtonElement>('button')].some(e=>shown(e)&&e.textContent==="適用"&&!e.disabled),'Unknown permits retry');button("現在のソース一式を再確認").click();await until(()=>!desktop.surface.uncertainField,'Recheck did not confirm actual result');await click("テーブルの詳細を再取得");await until(()=>!!document.querySelector('.table-declarations .ant-table')&&!document.querySelector("[aria-label=\"テーブル宣言の変更計画\"]"),'confirmed declaration did not reload');await close();checks.push('unknown-reply-explicit-recheck');
  assert(Number(desktop.surface.projection!.columns[0].field.key)===26,'actual result not adopted');assert(desktop.surface.projection!.rows.map(r=>r.id).join(',')===originalIds.join(','),'declaration edit changed record occurrences');assert(desktop.surface.status.dirty.join(',')===SOURCE,'schema writes dirtied dependent/other source');
  await desktop.selectTarget(SCHEMA,'declaration-schema-revisit',false);await desktop.selectTarget(SOURCE,'declaration-dirty-revisit',false);const p=desktop.surface.projection!;assert(p.rows[0].cells[11].display==='Held declaration draft'&&p.canUndo,'schema write/navigation dropped record history');
  const work=p.measurement.work;assert(work.projectDiscovery===0&&work.projectEnumeration===0&&work.projectYamlParse===0&&work.projectValidation===0,'warm navigation performed project-wide work');button("元に戻す").click();await until(()=>!desktop.surface.status.dirty.length,'Undo did not finish');assert(!desktop.surface.status.dirty.length,'record Undo did not restore bytes');assert(desktop.viewport!.getBoundingClientRect().top===top,'declaration feedback shifted grid');checks.push('dirty-revisit-undo-warm-zero-stable-grid');
  await invoke('evidence_write',{report:{checks,startup,work,visibility:document.visibilityState,focused:document.hasFocus(),columns:desktop.surface.projection!.columns.map(c=>c.field)}});
 }catch(error){await invoke('evidence_write',{report:{error:String(error),checks,startup,status:desktop.surface.status,focus:document.activeElement?.outerHTML.slice(0,600),drawer:[...document.querySelectorAll<HTMLElement>('.table-declarations')].filter(shown).map(e=>e.textContent?.slice(0,3500))}});}
}
