// GUI-SHELL-LANGUAGE-001: presentation only. Rust messages/codes and action IDs
// remain unchanged on the wire; technical placeholders are copied verbatim.
const actions: Record<string, string> = {
  Save: "保存", "Save All": "すべて保存", "Don't Save": "保存しない",
  Cancel: "キャンセル", Compare: "比較", Delete: "削除", Overwrite: "上書き",
  "Restore OLD": "変更前の状態に復元", "Reload source": "ソースを再読み込み",
  Reload: "再読み込み", "Clear Search": "検索を解除", "Project Settings": "プロジェクト設定",
};
const statuses: Record<string, string> = {
  Success: "成功", Conflict: "外部変更との競合", Failure: "失敗",
  OutcomeUnknown: "結果を確認できません", "Outcome Unknown": "結果を確認できません",
  NotAttempted: "未実行", RecoveryRequired: "復旧が必要です", "Recovery Required": "復旧が必要です",
  success: "成功", failure: "失敗", error: "エラー", warning: "警告", idle: "待機中",
  running: "実行中", completed: "完了", failed: "失敗", unknown: "結果を確認できません",
  succeeded: "成功", notAttempted: "未実行", outcome_unknown: "結果を確認できません", recovery_required: "復旧が必要です",
  cancelled: "キャンセル済み", not_attempted: "未実行", partial: "一部完了",
  csharp: "C#", binary: "MasterMemoryバイナリ", OLD: "変更前", NEW: "変更後",
};
export const actionLabel = (action: string): string => actions[action] ?? action;
export const statusLabel = (status: string): string => statuses[status] ?? status;
const messages: Record<string, string> = {
  "pending delete is not editable": "削除予定のレコードは編集できません",
  "record occurrence missing": "対象のレコードがありません",
  "project configuration changed; explicit Project reload required": "プロジェクト設定が変わりました。プロジェクトを再読み込みしてください",
  "source root binding changed": "ソースルートの対応付けが変わりました",
  "external source identity/binding changed": "ソースが外部で変更されたか対応付けが変わりました",
  "no current parseable document": "現在のソースを解析できません",
  "unobserved dependency": "依存するソースの状態が未確認です",
  "source or required semantic context changed": "ソースまたは必要な宣言が変更されています",
  "Table source required": "テーブルのソースが必要です",
  "source has no Table": "ソースがテーブルに対応していません",
  "field entry missing": "フィールドの宣言がありません",
  "Pending delete": "削除予定",
  "record source required; create/select a physical source": "レコードの保存先がありません。ソースを作成または選択してください",
  "all field shapes must resolve before Add Row": "行を追加する前にすべてのフィールドの型を解決してください",
  "Outcome Unknown; inspect and re-read the actual source before editing": "結果を確認できません。編集する前にソースを確認して読み直してください",
  "new record mapping requires a safely owned block sequence": "レコードの追加には安全に編集できるブロック形式のシーケンスが必要です",
  "resolved field required": "型を解決したフィールドが必要です",
  "draft revision changed": "未保存の変更が更新されています",
  "fresh observation and recovery required": "現在の状態の確認と復旧が必要です",
  "Nullable and Array are mutually exclusive": "Null許容と配列は同時に指定できません",
  "flow field membership needs structural localization": "フロー形式のフィールド構成を安全に特定できません",
  "observation required": "現在の状態の確認が必要です",
  "selected record source does not belong to current Table": "選択したレコードソースは現在のテーブルに属していません",
  "writes are gated": "書き込みを保護のため停止しています",
  "no automatic retry; observe actual source first": "自動再試行は行いません。先に現在のソースを確認してください",
  "another target failed preflight": "別の対象が事前確認に失敗しました",
  "external identity must be captured": "外部ソースの現在の識別情報の確認が必要です",
  "reviewed identity differs": "確認済みの識別情報と現在の状態が異なります",
  "request belongs to a previous Project session": "以前のプロジェクトの要求です",
  "selection superseded": "新しい選択に切り替わりました",
  "wait for the running mutation to finish, then switch Project explicitly": "実行中の変更が完了してからプロジェクトを切り替えてください",
  "saved input capture / structural operation is running; Save was not queued": "保存済み入力の取得または構造変更を実行中です。保存は予約していません",
  "workspace worker closed": "ワークスペースの処理が終了しました",
  "pending authoring operations are bounded; try after current operation": "現在の編集処理が完了してから再操作してください",
  "filesystem event backlog exceeded its bound; explicit Project Reload required": "外部変更の通知が多すぎます。プロジェクトを再読み込みしてください",
  "filesystem watcher lost events; explicit Project Reload required": "外部変更の通知が失われました。プロジェクトを再読み込みしてください",
  "running mutation must finish before Project switch": "実行中の変更が完了してからプロジェクトを切り替えてください",
  "Save All / Don't Save / Cancel required": "すべて保存・保存しない・キャンセルの確認が必要です",
  "created Project binding changed before workspace adoption": "作成したプロジェクトの対応付けが開く前に変わりました",
  "Open Project required": "プロジェクトを開いてください",
  "Build is blocked until source-set Recovery is established": "ソース一式の復旧を完了するまでビルドを停止しています",
  "Build / Publish / Migration operation is already running; retry explicitly after completion": "ビルド・配布・構造変更を実行中です。完了してから再操作してください",
  "delivery state is unavailable; inspect actual artifacts": "配布の状態を取得できません。現在の成果物を確認してください",
  "delivery state is unavailable": "配布の状態を取得できません",
  "delivery worker stopped unexpectedly; inspect actual artifacts / destinations before another write": "配布の処理が予期せず終了しました。次の書き込みの前に成果物と配布先を確認してください",
  "saved Project identity changed; reload Project": "保存済みプロジェクトの識別情報が変わりました。再読み込みしてください",
  "delivery state unavailable": "配布の状態を取得できません",
  "Build belongs to an obsolete Project": "以前のプロジェクトのビルドです",
  "preview is unavailable; request and confirm a new preview": "配布内容の確認情報を取得できません。新しく取得して確認してください",
  "Publish cancelled; canonical Build retained": "配布をキャンセルしました。成功済みのビルドは保持しています",
  "actual complete artifact set and every receipt hash verified": "成果物一式とすべてのレシートのハッシュを確認しました",
  "Build result changed": "ビルド結果が更新されています",
  "Build diagnostic unavailable": "ビルドの診断を取得できません",
  "Build snapshot unavailable": "ビルド時の内容を取得できません"
,
  "base-10 integer grammar required": "10進整数を入力してください",
  "integer outside representable range": "整数が表現可能な範囲を超えています",
  "unknown integer type": "整数の型を解決できません",
  "outside {target} range": "{target}の範囲を超えています",
  "non-null value required": "null以外の値が必要です",
  "unsupported source representation": "このソース表現には対応していません",
  "Array requires a sequence": "配列にはシーケンスが必要です",
  "type resolution depth exceeded": "型の参照が深すぎます",
  "scalar required": "スカラー値が必要です",
  "true or false required": "trueまたはfalseを入力してください",
  "fraction or exponent required": "小数または指数表記を使用してください",
  "finite floating value required": "有限の浮動小数点数が必要です",
  "unresolved type {target}": "型{target}を解決できません",
  "symbolic enum member required": "列挙型のメンバー名を指定してください",
  "unknown {target} member {name}": "{target}にメンバー{name}はありません",
  "Flags require a member sequence": "フラグにはメンバーのシーケンスが必要です",
  "symbolic Flags member required": "フラグのメンバー名を指定してください",
  "unknown / duplicate Flags member {name}": "フラグのメンバー{name}が不明、または重複しています",
  "None must appear alone; Flags cannot be empty": "Noneは単独で指定してください。フラグを空にはできません",
  "Custom requires a mapping": "カスタム型にはマッピングが必要です",
  "unknown Custom member": "カスタム型に宣言されていないメンバーです",
  "field entry required": "フィールドの宣言が必要です",
  "Array requires sequence": "配列にはシーケンスが必要です",
  "{key} must be unquoted boolean": "{key}には引用符なしの真偽値を指定してください",
  "{key} must be boolean": "{key}には真偽値を指定してください",
  "unknown member {}": "不明なメンバー: {0}",
  "unquoted non-negative integer key required": "キーには引用符なしの非負整数を指定してください",
  "key exceeds native MessagePack KeyAttribute range": "キーがMessagePack KeyAttributeの範囲を超えています",
  "invalid name/key/modifier or duplicate field": "名前・キー・修飾子が無効、またはフィールドが重複しています",
  "at least one field required": "少なくとも1つのフィールドが必要です",
  "non-empty unique resolved key components required": "キーの構成フィールドを解決できません。空・重複を確認してください",
  "duplicate key or generated query": "キーまたは生成されるクエリが重複しています",
  "duplicate Reference": "参照が重複しています",
  "exactly one category required": "型の種類を1つだけ指定してください",
  "unquoted integer declaration required": "引用符なしの整数を宣言してください",
  "invalid or duplicate member": "メンバーが無効、または重複しています",
  "None=0 and atomic bit members required": "None=0と単一ビットのメンバーが必要です",
  "required members missing": "必須のメンバーがありません",
  "integer key malformed": "整数キーの形式が不正です",
  "enum type missing": "列挙型がありません",
  "enum member missing": "列挙型のメンバーがありません",
  "key-compatible scalar required": "キーに使用できるスカラー値が必要です",
  "explicit TOML table required; dotted/inline representation is read-only": "明示的なTOMLテーブルが必要です。ドットキー・インライン表現は読み取り専用です",
  "table has no source span": "テーブルの書き込み位置を特定できません",
  "profile {name}: explicit table required": "プロファイル{name}: 明示的なテーブルが必要です",
  "{key}: string array required": "{key}: 文字列の配列が必要です",
  "{key}: non-string/ambiguous entry is read-only": "{key}: 文字列以外、または位置が曖昧な項目は読み取り専用です",
  "array separator cannot be safely located": "配列の区切り位置を安全に特定できません",
  "input cannot be represented losslessly": "入力を情報の損失なしで表現できません",
  "overlapping config edit spans": "設定の編集範囲が重なっています",
  "invalid config edit span": "設定の編集範囲が不正です",
  "Project root/config binding changed; reopen Project explicitly": "プロジェクトのルートまたは設定の対応付けが変わりました。プロジェクトを開き直してください",
  "explicit input discard confirmation required": "入力を破棄する確認が必要です",
  "config buffer revision changed; input retained": "設定が変更されています。入力は保持しました",
  "observe actual config before another operation": "次の操作の前にディスク上の設定を再確認してください",
  "TOML cannot be located safely": "TOMLの書き込み位置を安全に特定できません",
  "profile name must be lowercase kebab-case; input was not changed": "プロファイル名は小文字のkebab-caseで指定してください。入力は変更していません",
  "build table is unavailable": "build設定を取得できません",
  "inline profiles are read-only": "インラインのプロファイルは読み取り専用です",
  "profile already exists; input was not changed": "同名のプロファイルがあります。入力は変更していません",
  "profiles table is unavailable": "プロファイルの設定を取得できません",
  "explicit csharp or binary kind required": "種類にcsharpまたはbinaryを明示してください",
  "inline publish configuration is read-only": "インラインの配布設定は読み取り専用です",
  "publish.targets requires an array of explicit tables": "publish.targetsには明示的なテーブルの配列が必要です",
  "publish table is unavailable": "配布設定を取得できません",
  "targets array is unavailable": "配布先の配列を取得できません",
  "targets require explicit array tables": "配布先には明示的な配列テーブルが必要です",
  "target occurrence is unavailable": "対象の配布先を取得できません",
  "target path is absent": "配布先のパスがありません",
  "target path is not a locatable string": "配布先のパスの文字列位置を特定できません",
  "tag occurrence is unavailable": "対象のタグを取得できません",
  "profile table is unavailable": "プロファイルのテーブルを取得できません",
  "property key is unlocatable": "設定キーの位置を特定できません",
  "array is unlocatable": "配列の位置を特定できません",
  "new property boundary is ambiguous": "設定項目の追加位置が曖昧です",
  "new property acquired unrelated trivia": "追加した設定項目が無関係な書式に影響しています",
  "profile table header cannot be located": "プロファイルのテーブル見出しを特定できません",
  "edit changed an unrelated value or failed its exact target": "対象の値を正確に編集できなかったか、無関係な値が変わりました",
  "config Save was not retried; actual bytes must be observed": "設定の保存は再試行していません。ディスク上の内容を確認してください",
  "config is unchanged": "設定に変更はありません",
  "actual config matches the candidate": "ディスク上の設定は保存候補と一致しています",
  "actual config still matches the base; draft retained": "ディスク上の設定は編集元と一致しています。未保存の変更は保持しました",
  "actual config differs; Compare / Reload required": "ディスク上の設定が変わりました。比較または再読み込みが必要です",
  "Outcome Unknown: Recheck actual config before editing": "結果を確認できません。編集の前にディスク上の設定を再確認してください",
  "inline/non-table Profile is read-only": "インライン・非テーブル表現のプロファイルは読み取り専用です",
  "build.profiles: inline/non-table representation is read-only": "build.profiles: インライン・非テーブル表現は読み取り専用です",
  "{name}.{key}: unknown property is preserved; repair it in the source file": "{name}.{key}: 不明な設定項目を保持しています。ソースファイルで修正してください",
  "{name}: invalid Profile name is preserved; rename in the source file": "{name}: 無効なプロファイル名を保持しています。ソースファイルで名前を修正してください",
  "path is absent/non-string; repair it in the source file": "パスがないか文字列ではありません。ソースファイルで修正してください",
  "target {}.{key}: unknown property is preserved": "配布先{0}.{key}: 不明な設定項目を保持しています",
  "publish.targets: inline/non-array-table representation is read-only": "publish.targets: インライン・配列テーブル以外の表現は読み取り専用です",
  "lowercase kebab-case tag required": "タグは小文字のkebab-caseで指定してください",
  "duplicate tag": "タグが重複しています",
  "include/exclude overlap": "含めるタグと除外するタグが重複しています",
  "array has no source span": "配列の書き込み位置を特定できません",
  "array boundary cannot be located": "配列の境界を特定できません",
  "entry has no span": "項目の位置を特定できません",
  "tag occurrence unavailable": "対象のタグを取得できません",
  "diagnostic generation changed": "診断が更新されています",
  "source changed since diagnostic": "診断後にソースが変更されています",
  "diagnostic occurrence missing": "診断対象のレコードを取得できません",
  "Build configuration differs; run Build again before locating a record": "ビルド設定が異なります。レコードに移動する前に再ビルドしてください",
  "editor base is unavailable": "編集元の内容を取得できません",
  "Build snapshot differs from the editor base; run Build again before locating a record": "ビルド時の内容と編集元が異なります。レコードに移動する前に再ビルドしてください",
  "saved occurrence is unavailable": "保存済みの対象レコードを取得できません",
  "Primary Key cannot be nonunique": "主キーには重複を許可できません",
  "candidate uses unsupported source syntax": "変更候補に未対応のソース構文があります",
  "Data requires exactly one existing Table schema": "データには既存のテーブルスキーマが1つ必要です",
  "selected Table declaration is invalid": "選択したテーブルの宣言が無効です",
  "declaration identity already exists": "同じ識別子の宣言があります",
  "generated declaration name already exists or is reserved": "生成される宣言名が既存の名前または予約名と重なっています",
  "unknown artifact category": "ソースの種類が不明です",
  "no unused MessagePack key": "未使用のMessagePackキーがありません",
  "dry run compiled and reloaded the candidate; no artifacts were changed": "変更候補をコンパイルして読み直しました。成果物は変更していません",
  "source-set recovery must be established before Build": "ビルドの前にソース一式の復旧を完了してください",
  "{path}: source cannot be classified": "{path}: ソースの種類を判定できません",
  "{path}: type category cannot be classified": "{path}: 型の種類を判定できません",
  "{path}: unknown source kind": "{path}: ソースの種類が不明です",
  "logical type declaration is missing or ambiguous": "型の宣言がないか曖昧です",
  "target type declaration cannot be resolved": "対象の型の宣言を解決できません",
  "{name}: dependent declaration cannot be resolved": "{name}: 依存する宣言を解決できません",
  "{name}: dependent Table cannot be resolved": "{name}: 依存するテーブルを解決できません",
  "{path}: affected Reference source cannot be resolved": "{path}: 変更対象の参照ソースを解決できません",
  "{path}: data binding cannot be classified": "{path}: データの対応付けを判定できません",
  "Flags None=0 cannot be renamed": "フラグのNone=0は名前を変更できません",
  "member not found": "メンバーが見つかりません",
  "Flags None=0 cannot be dropped": "フラグのNone=0は削除できません",
  "field not found": "フィールドが見つかりません",
  "operation does not match the resolved type category": "操作が対象の型の種類と一致しません",
  "Enum operation required": "列挙型の操作が必要です",
  "Custom Type operation required": "カスタム型の操作が必要です",
  "Value Object operation required": "値オブジェクトの操作が必要です",
  "dependent value has unsupported source representation": "依存する値に未対応のソース表現があります",
  "symbolic occurrence is unsafe": "メンバー名の位置を安全に編集できません",
  "member is used by an existing value occurrence": "既存の値がこのメンバーを使用しています",
  "dependent occurrence is unsafe": "依存する値を安全に編集できません",
  "{name}: dependent type cannot be resolved": "{name}: 依存する型を解決できません",
  "explicit constant initializer required for existing Custom values": "既存のカスタム型の値に対する初期値を明示してください",
  "type declaration differs from semantic intent": "型の宣言が確認した変更内容と異なります",
  "{path}: transformed values or member order differ": "{path}: 変更後の値またはメンバーの順序が異なります",
  "transformed declarations differ from semantic intent": "変更後の宣言が確認した変更内容と異なります",
  "config filename must be masterdata.toml": "設定ファイル名はmasterdata.tomlである必要があります",
  "masterdata.toml was not found": "masterdata.tomlが見つかりません",
  "build.output requires explicit migration to build.artifact_dir or a csharp publish target": "build.outputをbuild.artifact_dirまたはcsharp配布先に移行してください",
  "build.binary_output requires explicit migration to canonical masterdata.bytes or a binary publish target": "build.binary_outputをmasterdata.bytesまたはbinary配布先に移行してください",
  "metadata and configured paths must not be empty": "メタデータと設定されたパスを空にはできません",
  "invalid profile {name}": "無効なプロファイル: {name}",
  "invalid target kind/path": "配布先の種類またはパスが無効です",
  "unsafe relative path {s}": "安全でない相対パス: {s}",
  "invalid / duplicate tags": "タグが無効、または重複しています",
  "source must have project-relative provenance": "ソースにはプロジェクトからの相対位置が必要です",
  "multiple schemas": "同じテーブルに複数のスキーマがあります",
  "duplicate type": "型が重複しています",
  "kind must be schema, data or type": "kindにはschema、data、typeのいずれかを指定してください",
  "data schema not found": "データのスキーマが見つかりません",
  "unknown field {}": "不明なフィールド: {0}",
  "record must be a mapping": "レコードはマッピングである必要があります",
  "duplicate {}": "重複しています: {0}",
  "unknown component": "宣言されていない構成要素です",
  "missing component": "必要な構成要素がありません",
  "source escaped configured roots": "ソースが設定されたルートの外にあります",
  "Table operation required": "テーブルの操作が必要です",
  "{name}: type declaration is ambiguous or missing": "{name}: 型の宣言がないか曖昧です",
  "logical Table declaration is ambiguous": "テーブルの宣言が曖昧です",
  "{path}: Table binding missing": "{path}: テーブルの対応付けがありません",
  "{path}: affected Reference schema cannot be resolved": "{path}: 変更対象の参照スキーマを解決できません",
  "field name or MessagePack key collides": "フィールド名またはMessagePackキーが重複しています",
  "field insertion position is outside schema": "フィールドの挿入位置がスキーマの外です",
  "{new_name}: field name already exists": "{new_name}: 同じフィールド名があります",
  "{}: Reference {} cannot be resolved": "{0}: 参照{1}を解決できません",
  "{field}: Key or Reference depends on this field": "{field}: キーまたは参照がこのフィールドに依存しています",
  "records missing": "レコードがありません",
  "record sequence required": "レコードのシーケンスが必要です",
  "record mapping required": "レコードのマッピングが必要です",
  "record already contains new field": "追加するフィールドが既にレコードにあります",
  "explicit constant initializer required": "初期値を明示してください",
  "record member rename collides": "変更後のメンバー名が重複しています",
  "logical Table cannot be resolved": "テーブルを解決できません",
  "{name}: key capability cannot be proved": "{name}: キーに使用できることを確認できません",
  "quote inside unquoted field": "引用符なしのフィールド内に引用符があります",
  "invalid delimiter or text after closing quote": "閉じる引用符の後の区切りまたは文字が不正です",
  "ragged rectangle": "貼り付ける各行の列数が異なります",
  "empty rectangle": "貼り付ける範囲が空です",
  "saved Table declaration is unavailable": "保存済みのテーブル宣言を取得できません",
  "saved Table declaration is ambiguous": "保存済みのテーブル宣言が曖昧です",
  "schema source is unavailable": "スキーマのソースを取得できません",
  "captured declaration occurrence is missing": "確認した宣言を取得できません",
  "unsupported declaration member": "未対応の宣言メンバーです",
  "Reference component is missing": "参照の構成フィールドがありません",
  "saved schema changed; reopen Table detail before reviewing this occurrence": "保存済みスキーマが変わりました。テーブルの詳細を開き直して確認してください",
  "field occurrence is missing": "対象のフィールドを取得できません",
  "non-negative integer key required": "キーには非負整数を指定してください",
  "key occurrence is missing": "対象のキーを取得できません",
  "Reference occurrence is missing": "対象の参照を取得できません",
  "declaration differs from the captured intent": "宣言が確認した変更内容と異なります",
  "{path}: incoming Reference declaration cannot be resolved": "{path}: このテーブルへの参照宣言を解決できません",
  "non-target declarations changed": "対象外の宣言が変更されています",
  "key field is missing": "キーのフィールドがありません",
  "key field is not key-capable": "このフィールドはキーに使用できません",
  "explicit constant initializer is not entered": "初期値が入力されていません",
  "Flags initializer needs member symbols": "フラグの初期値にはメンバー名が必要です",
  "duplicate initializer member": "初期値のメンバーが重複しています",
  "{name}: unknown initializer member": "{name}: 不明な初期値のメンバーです",
  "initializer input shape does not match the resolved field": "初期値の形式がフィールドの型と一致しません",
  "current type source is unavailable": "現在の型ソースを取得できません",
  "type source changed; confirm the current declaration before requesting a Plan": "型ソースが変更されています。計画の作成前に現在の宣言を確認してください",
  "initializer is only available for Add Custom Field": "初期値はカスタム型フィールドの追加でのみ指定できます",
  "one initializer input is required": "初期値の入力が1つ必要です",
  "source mutation is gated": "ソースの編集を保護のため停止しています",
  "source/schema/type changed during preflight": "事前確認中にソース・スキーマ・型が変更されました",
  "fresh observation required": "現在の状態の再確認が必要です",
  "paste anchor missing": "貼り付けの開始位置がありません",
  "paste exceeds source rows": "貼り付ける範囲がソースの行数を超えています",
  "paste exceeds schema fields": "貼り付ける範囲がスキーマの列数を超えています",
  "exact rectangle with unique targets required": "重複しない対象の矩形範囲を指定してください",
  "existing key is not a paste target": "既存のキーは貼り付け先にできません",
  "paste candidate differs from exact targets": "貼り付け候補が対象範囲と一致しません",
  "null or complex value cannot be copied as scalar TSV": "nullまたは複合値はスカラーのTSVとしてコピーできません",
  "range authoring requires scalar leaf fields": "範囲編集にはスカラーのフィールドが必要です",
  "one neighbouring position required": "隣接する位置を1つ指定してください",
  "new record mapping requires a block sequence": "新しいレコードにはブロック形式のシーケンスが必要です",
  "insert occurrence missing": "挿入位置のレコードがありません",
  "Pending Delete requires safely owned block item bytes": "削除予定の行の範囲を安全に特定できません",
  "Delete altered another occurrence": "削除が他のレコードに影響しています",
  "Pending Delete occurrence required": "削除予定のレコードが必要です",
  "clear Search before source-position operations": "並べ替え・挿入の前に検索を解除してください",
  "reorder differs from exact occurrence permutation": "並べ替え結果が指定したレコード順序と一致しません",
  "schema revision changed": "スキーマが変更されています",
  "fields sequence required": "フィールドのシーケンスが必要です",
  "column order differs": "列の順序が異なります",
  "explicit record-bearing source required": "レコードを含む保存先のソースを明示してください",
  "unsafe records region": "レコードの範囲を安全に編集できません",
  "exact occurrence permutation required": "対象レコードの正確な順序を指定してください",
  "unknown occurrence": "対象のレコードを取得できません",
  "insert changed unrelated items": "挿入が無関係な項目に影響しています",
  "empty container restoration ambiguous": "空のコンテナーを安全に復元できません",
  "external config changed; Compare / Reload required": "設定が外部で変更されています。比較または再読み込みが必要です",
  "Recovery Required: config edits and Save are gated": "復旧が必要です。設定の編集と保存を停止しています",
  "config writes are gated": "設定の書き込みを保護のため停止しています",
  "saved config requires explicit Project Reload; existing drafts are retained": "保存済み設定を反映するにはプロジェクトの再読み込みが必要です。未保存の変更は保持しています",
  "config Save did not succeed": "設定を保存できませんでした",
  "source creation is gated": "ソースの作成を保護のため停止しています",
  "exactly one configured source root required": "設定済みのソースルートを1つ指定してください",
  "source file extension must be .yaml or .yml": "ソースの拡張子は.yamlまたは.ymlにしてください",
  "Recheck destination before another creation attempt": "作成を再試行する前に保存先を再確認してください",
  "E-CREATE-CONFLICT: destination already exists": "E-CREATE-CONFLICT: 保存先が既に存在します",
  "no uncertain creation at this destination": "この保存先に未確定の作成操作はありません",
  "Recheck confirmed no destination; explicit retry is available": "保存先が存在しないことを確認しました。明示的に再試行できます",
  "Recheck confirmed complete destination": "保存先の作成が完了していることを確認しました",
  "Recheck found a different destination; existing entry preserved": "保存先の内容が異なります。既存の項目は保持しました",
  "record location is ambiguous": "レコードの位置が曖昧です",
  "Tag location is ambiguous": "タグの位置が曖昧です",
  "Tag entry location is ambiguous": "タグ項目の位置が曖昧です",
  "adding Tags requires a block record mapping": "タグの追加にはブロック形式のレコードが必要です",
  "Tags must be a sequence of strings; edit this source externally to repair its shape": "タグには文字列のシーケンスが必要です。外部エディターでソースの形式を修正してください",
  "Use lowercase kebab-case": "小文字のkebab-caseで指定してください",
  "Duplicate Tag": "タグが重複しています",
  "Tag entry missing": "タグの項目がありません",
  "Tag edit altered a domain value": "タグの編集がデータの値に影響しています",
  "Tag candidate differs from exact entries": "タグの変更候補が対象の項目と一致しません",
  "Outcome Unknown: source observation required": "結果を確認できません。現在のソースを再確認してください",
  "Flags member operations use the parent control": "フラグのメンバーは親の値で編集してください",
  "target source representation is unsafe": "対象のソース表現を安全に編集できません",
  "scalar leaf required": "スカラーの末端の値が必要です",
  "Nullable value required": "Nullを許可する値が必要です",
  "enter a scalar value explicitly": "スカラー値を入力してください",
  "declared Enum member required": "宣言済みの列挙型メンバーが必要です",
  "declared Flags member required": "宣言済みのフラグメンバーが必要です",
  "Array required": "配列が必要です",
  "sequence required": "シーケンスが必要です",
  "Array occurrence missing": "対象の配列要素がありません",
  "Array destination missing": "配列の移動先がありません",
  "Array neighbouring position required": "隣接する配列要素を指定してください",
  "Array destination outside source": "配列の移動先がソースの外です",
  "complex operation changed record membership": "複合値の操作がレコード構成に影響しています",
  "Array occurrence count differs": "配列要素の数が異なります",
  "unknown source member; preserved until an explicit structural repair": "未宣言のソースメンバーを保持しています。構造を明示的に修正するまで変更しません",
  "source member missing": "ソースのメンバーがありません",
  "unsafe source representation": "ソース表現を安全に編集できません",
  "field path required": "フィールドのパスが必要です",
  "exact Array occurrence identity required": "配列要素の正確な識別情報が必要です",
  "path descends into a scalar": "スカラー値の中に子の値を指定しています",
  "diagnostic field missing": "診断対象のフィールドがありません",
  "diagnostic parent missing": "診断対象の親の値がありません",
  "diagnostic element index invalid": "診断対象の要素番号が無効です",
  "diagnostic element missing": "診断対象の要素がありません",
  "diagnostic member missing": "診断対象のメンバーがありません",
  "Recheck both old and new paths before another mutation": "次の編集の前に変更前・変更後の両方のパスを再確認してください",
  "path mutations are gated": "パスの変更を保護のため停止しています",
  "Save / Don't Save / Cancel required for this source": "このソースを保存・破棄・キャンセルする確認が必要です",
  "source outcome must be rechecked": "ソースの書き込み結果を再確認してください",
  "source root required": "ソースルートが必要です",
  "source changed; refresh before requesting Rename / Move": "ソースが変更されています。名前変更・移動の前に更新してください",
  "invalid move token": "移動の確認情報が無効です",
  "move review is unavailable; request a new review explicitly": "移動の確認情報を取得できません。現在のソースで確認し直してください",
  "no uncertain path mutation": "未確定のパス変更はありません",
  "destination changed after rename": "名前変更後に保存先が変更されています",
  "Recheck source outcome before discard": "破棄する前にソースの書き込み結果を再確認してください",
  "authoring mutations are gated": "編集を保護のため停止しています",
  "invalid Plan token": "変更計画の識別情報が無効です",
  "schema changed before structural authoring": "構造変更の前にスキーマが変更されています",
  "schema binding required": "スキーマの対応付けが必要です",
  "the current schema source is required": "現在のスキーマソースが必要です",
  "insertion neighbor is unavailable": "挿入位置に隣接する対象を取得できません",
  "scope is unavailable; confirm the command again": "変更範囲を取得できません。操作を確認し直してください",
  "the requested command differs from the captured scope": "操作が確認した変更範囲と一致しません",
  "structural writes are gated": "構造変更の書き込みを保護のため停止しています",
  "{path}: Save / Don't Save / Cancel required for affected sources": "{path}: 変更対象のソースを保存・破棄・キャンセルする確認が必要です",
  "{path}: source outcome must be rechecked": "{path}: ソースの書き込み結果を再確認してください",
  "Plan is unavailable; request a new Plan explicitly": "変更計画を取得できません。現在のソースで計画を作り直してください",
  "source is not affected by this Plan": "このソースは変更計画の対象ではありません",
  "operation was already attempted; Recheck its result without repeating the write": "この操作は実行済みです。書き込みを繰り返さず結果を再確認してください",
  "actual source could not be observed": "現在のソースを確認できません",
  "attempt information is unavailable": "操作の実行情報を取得できません",
  "no completed attempt is available": "完了した操作の情報がありません",
  "Table schema binding changed; select its current source": "テーブルとスキーマの対応付けが変わりました。現在のソースを選択してください",
  "copy anchor missing": "コピーの開始位置がありません",
  "copy focus missing": "コピーの終了位置がありません"
};
const escape = (text: string) => text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const templates = Object.entries(messages).filter(([text]) => text.includes("{")).sort(([a], [b]) => b.replace(/\{[^{}]*\}/g, "").length - a.replace(/\{[^{}]*\}/g, "").length).map(([text, translated]) => {
  const names: string[] = []; let position = 0, expression = "^";
  for (const match of text.matchAll(/\{([^{}]*)\}/g)) {
    expression += escape(text.slice(position, match.index)) + "(.+?)";
    names.push(match[1] || String(names.length)); position = match.index! + match[0].length;
  }
  return { pattern: new RegExp(expression + escape(text.slice(position)) + "$", "s"), names, translated };
});
export function uiMessage(text: string | null | undefined): string {
  if (!text) return "";
  if (messages[text]) return messages[text];
  if (statuses[text]) return statuses[text];
  for (const {pattern, names, translated} of templates) {
    const match = pattern.exec(text);
    if (match) return translated.replace(/\{([^{}]+)\}/g, (token, name) => {
      const index = names.indexOf(name); return index < 0 ? token : match[index + 1];
    });
  }
  const prefix = /^([^:\n]+): ([\s\S]+)$/.exec(text);
  if (prefix) return `${statusLabel(prefix[1])}: ${uiMessage(prefix[2])}`;
  // Unknown native/tool details stay verbatim; never infer domain meaning here.
  return text;
}

export function complexSummary(display: string, complex: boolean): string {
  if (!complex) return display;
  if (display === "(missing)") return "（未指定）";
  return display.replace(/^\[(\d+) items\]$/, "[$1 要素]").replace(/^\{(\d+) fields\}$/, "{$1 フィールド}");
}
