import {invoke} from "@tauri-apps/api/core";
import {desktop} from "./workspace";
import type {TypeProjection} from "./types";
const frame=()=>new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));
async function until(test:()=>boolean,message:string){const deadline=performance.now()+10000;while(!test()){if(performance.now()>deadline)throw new Error(message);await frame();}}
function assert(test:unknown,message:string):asserts test{if(!test)throw new Error(message);}
function visible(element:Element){return !!element.getClientRects().length;}
function button(label:string){const element=[...document.querySelectorAll<HTMLButtonElement>('button')].find(b=>visible(b)&&(b.getAttribute('aria-label')===label||b.textContent===label));assert(element,`missing button ${label}`);return element;}
function input(label:string){const element=[...document.querySelectorAll<HTMLInputElement>(`input[aria-label="${label}"]`)].find(visible);assert(element,`missing input ${label}`);return element;}
function text(label:string,value:string){const element=input(label);Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(element,value);element.dispatchEvent(new Event('input',{bubbles:true}));}
async function choice(label:string,value:string){const element=input(label);element.focus();element.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',keyCode:40,which:40,bubbles:true}));await until(()=>[...document.querySelectorAll<HTMLElement>('.ant-select-item-option-content')].some(el=>visible(el)&&el.textContent===value),`missing ${value} option`);[...document.querySelectorAll<HTMLElement>('.ant-select-item-option-content')].find(el=>visible(el)&&el.textContent===value)!.click();}
async function menu(label:string,action:string){button(label).click();await until(()=>[...document.querySelectorAll<HTMLElement>('[role="menuitem"]')].some(el=>visible(el)&&el.textContent===action),`missing ${action}`);[...document.querySelectorAll<HTMLElement>('[role="menuitem"]')].find(el=>visible(el)&&el.textContent===action)!.click();}
async function selected(source:string):Promise<TypeProjection>{await desktop.selectTarget(source,"type-workflow",false);const p=desktop.surface.typeProjection;assert(p?.clicked===source&&!desktop.surface.pending,"Type selection did not resolve");document.querySelector<HTMLElement>('[aria-label="Type Editor"]')!.focus();return p;}
async function plan(){button('Review change').click();await until(()=>!!document.querySelector('[aria-label="Type Migration Plan"]'),"Type Plan missing");await until(()=>document.activeElement?.getAttribute('aria-label')==='Type Migration Plan',"Plan lost keyboard focus");}
async function applied(test:()=>boolean,destructive=false){button('Apply').click();if(destructive){await until(()=>!!desktop.surface.choice,"destructive authorization missing");await until(()=>[...document.querySelectorAll<HTMLButtonElement>('button')].some(el=>visible(el)&&el.textContent==='Delete'),"Delete confirmation not rendered");button('Delete').click();}await until(()=>test()&&!document.querySelector('[aria-label="Type Migration Plan"]'),"Type Apply did not update the current declaration");}
async function compare(){button('Compare').click();await until(()=>!!document.querySelector('input[aria-label="Compare source"]'),"Type Compare missing");assert(desktop.surface.comparison?.migration,"Compare is not tied to captured Plan");button('Close').click();await until(()=>!!document.querySelector('[aria-label="Type Migration Plan"]'),"Compare lost Type Plan");}
export async function run({startup}:{startup:Record<string,unknown>}) {
  const checks:string[]=[];
  try {
    await until(()=>!!desktop.surface.inventory,"Project not open");
    for(const [source,category] of [["sources/item-id.yaml","valueObject"],["sources/rarity.yaml","enum"],["sources/item-tags.yaml","enum"],["sources/reward.yaml","custom"]]){
      const p=await selected(source);assert(p.declaration.category===category,"wrong category");
      for(const count of ['projectDiscovery','projectEnumeration','projectYamlParse','projectValidation'] as const)assert(p.measurement.work[count]===0,"Type warm project-wide work");
    }
    checks.push('resolved-type-selection-warm-zero');
    const custom=await selected('sources/reward.yaml');
    for(const which of [0,13]) {
      const trigger=button('itemId field actions');trigger.focus();trigger.click();
      await until(()=>[...document.querySelectorAll<HTMLElement>('[role="menuitem"]')].some(el=>visible(el)&&el.textContent==='Rename…'),"keyboard menu missing");
      const rename=[...document.querySelectorAll<HTMLElement>('[role="menuitem"]')].find(el=>visible(el)&&el.textContent==='Rename…')!;rename.focus();
      const enter=new KeyboardEvent('keydown',{key:'Enter',keyCode:which,which,bubbles:true,cancelable:true});rename.dispatchEvent(enter);
      assert(enter.defaultPrevented,"handled Menu Enter left native activation pending");
      await until(()=>!!document.querySelector('input[aria-label="Type operation name"]'),"Enter did not activate Rename");
      await until(()=>document.activeElement?.getAttribute('aria-label')==='Type operation name',"keyboard operation did not focus input");
      input('Type operation name').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',keyCode:27,which:27,bubbles:true}));
      await until(()=>document.activeElement?.getAttribute('aria-label')==='itemId field actions',"keyboard cancel did not restore origin");
    }
    assert(desktop.surface.typeProjection?.identity===custom.identity,"opening and cancelling Type operation changed source");
    checks.push('type-keyboard-menu-cancel-focus');
    await desktop.selectTarget('sources/independent.yaml','type-unrelated-draft',false);const unrelated=desktop.surface.projection!;await desktop.rpc({kind:'editText',epoch:unrelated.sessionEpoch,source:unrelated.source,revision:unrelated.revision,generation:unrelated.generation,row:unrelated.rows[0].id,field:'id',text:'2'});await until(()=>desktop.surface.status.dirty.includes('sources/independent.yaml'),"unrelated dirty draft not observed");
    await selected('sources/item-id.yaml');button('Edit conversions').click();await until(()=>[...document.querySelectorAll<HTMLElement>('.ant-checkbox-wrapper')].some(el=>visible(el)&&el.textContent==='Implicit from underlying'),"conversion input missing");
    [...document.querySelectorAll<HTMLElement>('.ant-checkbox-wrapper')].find(el=>visible(el)&&el.textContent==='Implicit from underlying')!.click();
    await plan();await compare();await applied(()=>desktop.surface.typeProjection?.declaration.category==='valueObject'&&desktop.surface.typeProjection.declaration.from_implicit);
    checks.push('value-object-plan-diff-apply');
    await selected('sources/item-tags.yaml');assert(!document.querySelector('[aria-label="None member actions"]'),"None offers Rename or Drop");checks.push('flags-none-protected');
    await selected('sources/ranges.yaml');button('Add member').click();await until(()=>!!document.querySelector('input[aria-label="Type operation name"]'),"member input missing");text('Type operation name','Max');text('Member numeric value','18446744073709551615');await plan();
    const identity=desktop.surface.typeProjection!.identity;await invoke('evidence_write',{report:{phase:'type-stale'}});await until(()=>desktop.surface.typeProjection?.identity!==identity&&!desktop.surface.pending,"external type change was not observed");button('Apply').click();await until(()=>[...document.querySelectorAll<HTMLButtonElement>('button')].some(el=>visible(el)&&el.textContent==='Re-plan current source'),"stale Apply did not offer explicit Re-plan");assert(desktop.surface.typeProjection?.declaration.category==='enum'&&!desktop.surface.typeProjection.declaration.members.some(([n])=>n==='Max'),"stale Plan wrote a member");button('Re-plan current source').click();await until(()=>!!document.querySelector('[aria-label="Type Migration Plan"]')&&!button('Apply').disabled,"Re-plan did not retain exact input");checks.push('external-stale-plan-explicit-replan');
    await applied(()=>desktop.surface.typeProjection?.declaration.category==='enum'&&desktop.surface.typeProjection.declaration.members.some(([n,v])=>n==='Max'&&v==='18446744073709551615'));checks.push('enum-ulong-lossless-add');
    await menu('Max member actions','Rename…');await until(()=>!!document.querySelector('input[aria-label="Type operation name"]'),"Rename input missing");text('Type operation name','Maximum');await plan();await applied(()=>desktop.surface.typeProjection?.declaration.category==='enum'&&desktop.surface.typeProjection.declaration.members.some(([n,v])=>n==='Maximum'&&v==='18446744073709551615'));checks.push('enum-rename-preserves-number');
    await menu('Maximum member actions','Drop…');await until(()=>[...document.querySelectorAll<HTMLButtonElement>('button')].some(el=>visible(el)&&el.textContent==='Review change'),"Drop input missing");await plan();await compare();await applied(()=>desktop.surface.typeProjection?.declaration.category==='enum'&&!desktop.surface.typeProjection.declaration.members.some(([n])=>n==='Maximum'),true);checks.push('unused-member-authorized-drop');
    await selected('sources/reward.yaml');button('Add field').click();await until(()=>!!document.querySelector('input[aria-label="Custom field name"]'),"Custom input missing");text('Custom field name','minimum');await choice('Custom field base type','long');
    await until(()=>!!document.querySelector('[aria-label="Typed constant initializer"]'),"typed initializer missing");
    const required=[...document.querySelectorAll<HTMLElement>('.ant-radio-wrapper')].find(el=>visible(el)&&el.textContent==='Required');assert(required,"modifier input missing");required.click();
    button('Review change').click();await until(()=>[...document.querySelectorAll<HTMLElement>('.ant-alert')].some(el=>visible(el)&&el.textContent?.includes('explicit constant initializer')),"unset initializer was accepted");
    button('Enter value').click();await until(()=>!!document.querySelector('input[aria-label="Initializer scalar"]'),"guided scalar missing");text('Initializer scalar','-9223372036854775808');await plan();await compare();await applied(()=>desktop.surface.typeProjection?.declaration.category==='custom'&&desktop.surface.typeProjection.declaration.fields.some(f=>f.name==='minimum'&&f.typeName==='long'));checks.push('custom-long-min-guided-initializer');
    await menu('minimum field actions','Rename…');await until(()=>!!document.querySelector('input[aria-label="Type operation name"]'),"Custom Rename missing");text('Type operation name','lower');await plan();await applied(()=>desktop.surface.typeProjection?.declaration.category==='custom'&&desktop.surface.typeProjection.declaration.fields.some(f=>f.name==='lower'));await until(()=>document.activeElement?.getAttribute('aria-label')==='lower field actions',"renamed field lost origin focus");checks.push('custom-rename-occurrences');
    await menu('lower field actions','Drop…');await until(()=>[...document.querySelectorAll<HTMLButtonElement>('button')].some(el=>visible(el)&&el.textContent==='Review change'),"Custom Drop input missing");await plan();await applied(()=>desktop.surface.typeProjection?.declaration.category==='custom'&&!desktop.surface.typeProjection.declaration.fields.some(f=>f.name==='lower'),true);checks.push('custom-authorized-drop');
    await desktop.selectTarget('sources/catalog-data.yaml','type-dirty-setup',false);const data=desktop.surface.projection!;await desktop.rpc({kind:'editText',epoch:data.sessionEpoch,source:data.source,revision:data.revision,generation:data.generation,row:data.rows[0].id,field:'name',text:'local type workflow'});await until(()=>desktop.surface.status.dirty.includes('sources/catalog-data.yaml'),"dirty source not observed");
    await selected('sources/rarity.yaml');await menu('Rare member actions','Rename…');await until(()=>!!document.querySelector('input[aria-label="Type operation name"]'),"affected dirty Rename missing");text('Type operation name','Epic');await plan();assert(button('Apply').disabled,"affected dirty Apply was enabled");assert(document.querySelector('[aria-label="Type Migration Plan"]')!.textContent!.includes('sources/catalog-data.yaml'),"affected dirty source is not identifiable");button('Cancel').click();await desktop.selectTarget('sources/catalog-data.yaml','type-dirty-return',false);assert(desktop.surface.projection!.dirty&&desktop.surface.projection!.rows[0].cells.find((_,i)=>desktop.surface.projection!.columns[i].field.name==='name')!.display==='local type workflow',"Type Plan lost data draft");checks.push('affected-dirty-plan-apply-gate');
    assert((startup.browserErrors as string[]).length===0,"browser errors");
    await desktop.selectTarget('sources/independent.yaml','type-unrelated-return',false);assert(desktop.surface.projection?.dirty&&desktop.surface.projection.canUndo&&desktop.surface.projection.rows[0].cells[0].display==='2',"unrelated draft or history was lost");checks.push('unrelated-draft-history-survives-apply');
    await invoke('evidence_write',{report:{kind:'type',checks,dirty:desktop.surface.status.dirty,samples:desktop.samples,visibility:document.visibilityState,focused:document.hasFocus(),startup}});
  }catch(error){await invoke('evidence_write',{report:{kind:'type',error:String(error),checks,startup,status:desktop.surface.status,typeProjection:desktop.surface.typeProjection,surfaceError:desktop.surface.error,active:document.activeElement?.outerHTML.slice(0,1000),dialog:[...document.querySelectorAll('[role="dialog"]')].find(visible)?.outerHTML}});}
}
