use std::fmt::Write;
use std::path::Path;

use masterdata_core::{BuildPlan, ErrorKind, MasterdataError, Result, SchemaDocument};

use crate::model::{CSharpGenerationPlan, GeneratedFile, GenerationNote};

#[derive(Debug, Clone)]
pub struct CSharpGenerator {
    namespace: String,
}

impl Default for CSharpGenerator {
    fn default() -> Self {
        Self::new("Masterdata.Generated")
    }
}

impl CSharpGenerator {
    pub fn new(namespace: impl Into<String>) -> Self {
        Self {
            namespace: namespace.into(),
        }
    }

    pub fn plan(&self, build_plan: &BuildPlan) -> Result<CSharpGenerationPlan> {
        let schemas: Vec<_> = build_plan.documents.schemas().collect();
        if schemas.is_empty() {
            return Err(MasterdataError::new(
                "CODEGEN-SCHEMA-001",
                ErrorKind::NotImplemented,
                "C# generation requires at least one schema document",
            ));
        }

        let mut files = Vec::with_capacity(schemas.len());
        for (_, schema) in schemas {
            files.push(render_schema(&self.namespace, schema)?);
        }
        Ok(CSharpGenerationPlan {
            namespace: self.namespace.clone(),
            files,
            notes: vec![GenerationNote {
                message: "MasterMemory attributes, Source Generator integration, and binary output are not implemented in this scaffold.".to_owned(),
                placeholder: true,
            }],
        })
    }

    pub fn write_to(
        &self,
        plan: &CSharpGenerationPlan,
        output_dir: &Path,
    ) -> Result<Vec<std::path::PathBuf>> {
        std::fs::create_dir_all(output_dir).map_err(|error| {
            MasterdataError::new(
                "CODEGEN-IO-001",
                ErrorKind::Io,
                format!("could not create C# output directory: {error}"),
            )
            .with_source(output_dir.to_path_buf())
        })?;
        let mut written = Vec::with_capacity(plan.files.len());
        for file in &plan.files {
            let path = output_dir.join(&file.relative_path);
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent).map_err(|error| {
                    MasterdataError::new(
                        "CODEGEN-IO-002",
                        ErrorKind::Io,
                        format!("could not create C# output directory: {error}"),
                    )
                    .with_source(parent.to_path_buf())
                })?;
            }
            std::fs::write(&path, &file.contents).map_err(|error| {
                MasterdataError::new(
                    "CODEGEN-IO-003",
                    ErrorKind::Io,
                    format!("could not write generated C#: {error}"),
                )
                .with_source(path.clone())
            })?;
            written.push(path);
        }
        Ok(written)
    }
}

fn render_schema(namespace: &str, schema: &SchemaDocument) -> Result<GeneratedFile> {
    let type_name = schema
        .csharp_name
        .clone()
        .unwrap_or_else(|| pascal_case(&schema.table));
    if !is_csharp_identifier(&type_name) {
        return Err(MasterdataError::new(
            "CODEGEN-NAME-001",
            ErrorKind::Validation,
            format!("`{type_name}` is not a valid C# type identifier"),
        ));
    }

    let mut document = CSharpDocument::new();
    document.line("// <auto-generated />");
    document
        .line("// Scaffold only: MasterMemory source generation is intentionally not emitted yet.");
    document.line("#nullable enable");
    document.line("");
    document.line(format!("namespace {namespace};"));
    document.line("");
    document.line(format!("public sealed partial class {type_name}"));
    document.line("{");
    for field in &schema.fields {
        let field_name = pascal_case(&field.name);
        if !is_csharp_identifier(&field_name) {
            return Err(MasterdataError::new(
                "CODEGEN-NAME-002",
                ErrorKind::Validation,
                format!("`{}` is not a valid C# field identifier", field.name),
            ));
        }
        document.line(format!(
            "    public {} {field_name} {{ get; }}",
            csharp_type(&field.type_name)?
        ));
    }
    if !schema.fields.is_empty() {
        document.line("");
        document.line(format!("    public {type_name}("));
        for (index, field) in schema.fields.iter().enumerate() {
            let separator = if index + 1 == schema.fields.len() {
                ""
            } else {
                ","
            };
            document.line(format!(
                "        {} {}{}",
                csharp_type(&field.type_name)?,
                camel_case(&field.name),
                separator
            ));
        }
        document.line("    )");
        document.line("    {");
        for field in &schema.fields {
            let field_name = pascal_case(&field.name);
            document.line(format!(
                "        {field_name} = {};",
                camel_case(&field.name)
            ));
        }
        document.line("    }");
    }
    document.line("}");

    Ok(GeneratedFile {
        relative_path: std::path::PathBuf::from(format!("{}.g.cs", type_name)),
        contents: document.finish(),
    })
}

struct CSharpDocument {
    lines: Vec<String>,
}

impl CSharpDocument {
    fn new() -> Self {
        Self { lines: Vec::new() }
    }

    fn line(&mut self, line: impl Into<String>) {
        self.lines.push(line.into());
    }

    fn finish(self) -> String {
        let mut output = self.lines.join("\n");
        output.push('\n');
        output
    }
}

fn csharp_type(type_name: &str) -> Result<&'static str> {
    match type_name {
        "bool" => Ok("bool"),
        "byte" | "uint8" => Ok("byte"),
        "short" | "int16" => Ok("short"),
        "int" | "int32" => Ok("int"),
        "long" | "int64" => Ok("long"),
        "sbyte" => Ok("sbyte"),
        "ushort" | "uint16" => Ok("ushort"),
        "uint" | "uint32" => Ok("uint"),
        "ulong" | "uint64" => Ok("ulong"),
        "float" => Ok("float"),
        "double" => Ok("double"),
        "string" => Ok("string"),
        "" => Err(MasterdataError::new(
            "CODEGEN-TYPE-001",
            ErrorKind::Validation,
            "schema field type must not be empty",
        )),
        other => Err(MasterdataError::new(
            "CODEGEN-TYPE-002",
            ErrorKind::NotImplemented,
            format!("custom C# type `{other}` is reserved for a future schema/type generator"),
        )),
    }
}

fn pascal_case(value: &str) -> String {
    value
        .split(['-', '_', ' ', '.'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn camel_case(value: &str) -> String {
    let pascal = pascal_case(value);
    let mut chars = pascal.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

fn is_csharp_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    match chars.next() {
        Some(first) if first == '_' || first.is_ascii_alphabetic() => {}
        _ => return false,
    }
    chars.all(|character| character == '_' || character.is_ascii_alphanumeric())
}

#[allow(dead_code)]
fn _format_note(note: &GenerationNote) -> String {
    let mut text = String::new();
    let _ = write!(&mut text, "{}", note.message);
    text
}
