use std::collections::BTreeSet;
use std::fmt::Write;
use std::path::Path;

use masterdata_core::{BuildPlan, ErrorKind, MasterdataError, Result, SchemaDocument};

use crate::model::{CSharpGenerationPlan, GeneratedFile, GenerationNote};

#[derive(Debug, Clone)]
pub struct CSharpGenerator {
    namespace: String,
}

impl Default for CSharpGenerator {
    fn default() -> Self {
        Self::new("Masterdata.Generated")
    }
}

impl CSharpGenerator {
    pub fn new(namespace: impl Into<String>) -> Self {
        Self {
            namespace: namespace.into(),
        }
    }

    pub fn plan(&self, build_plan: &BuildPlan) -> Result<CSharpGenerationPlan> {
        validate_namespace(&self.namespace)?;
        let schemas: Vec<_> = build_plan.documents.schemas().collect();
        if schemas.is_empty() {
            return Err(MasterdataError::new(
                "E-CODEGEN-NO-SCHEMA",
                ErrorKind::NotImplemented,
                "C# generation requires at least one schema document",
            ));
        }

        let mut files = Vec::with_capacity(schemas.len());
        let mut generated_type_names = BTreeSet::new();
        let mut generated_file_names = BTreeSet::new();
        for (_, schema) in schemas {
            let type_name = generated_type_name(schema);
            if !generated_type_names.insert(type_name.clone()) {
                return Err(MasterdataError::new(
                    "E-CODEGEN-TYPE-NAME-COLLISION",
                    ErrorKind::Validation,
                    format!("multiple schemas generate the C# type/file name `{type_name}`"),
                ));
            }
            let filename_key = type_name.to_ascii_lowercase();
            if !generated_file_names.insert(filename_key) {
                return Err(MasterdataError::new(
                    "E-CODEGEN-FILENAME-COLLISION",
                    ErrorKind::Validation,
                    format!(
                        "multiple schemas generate filenames that collide case-insensitively with `{type_name}.g.cs`"
                    ),
                ));
            }
            files.push(render_schema(&self.namespace, schema)?);
        }
        Ok(CSharpGenerationPlan {
            namespace: self.namespace.clone(),
            files,
            notes: vec![GenerationNote {
                message: "MasterMemory attributes, Source Generator integration, and binary output are not implemented in this scaffold.".to_owned(),
                placeholder: true,
            }],
        })
    }

    pub fn write_to(
        &self,
        plan: &CSharpGenerationPlan,
        output_dir: &Path,
    ) -> Result<Vec<std::path::PathBuf>> {
        std::fs::create_dir_all(output_dir).map_err(|error| {
            MasterdataError::new(
                "E-CODEGEN-OUTPUT-CREATE",
                ErrorKind::Io,
                format!("could not create C# output directory: {error}"),
            )
            .with_source(output_dir.to_path_buf())
        })?;
        let mut written = Vec::with_capacity(plan.files.len());
        for file in &plan.files {
            let path = output_dir.join(&file.relative_path);
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent).map_err(|error| {
                    MasterdataError::new(
                        "E-CODEGEN-OUTPUT-PARENT-CREATE",
                        ErrorKind::Io,
                        format!("could not create C# output directory: {error}"),
                    )
                    .with_source(parent.to_path_buf())
                })?;
            }
            std::fs::write(&path, &file.contents).map_err(|error| {
                MasterdataError::new(
                    "E-CODEGEN-OUTPUT-WRITE",
                    ErrorKind::Io,
                    format!("could not write generated C#: {error}"),
                )
                .with_source(path.clone())
            })?;
            written.push(path);
        }
        Ok(written)
    }
}

fn render_schema(namespace: &str, schema: &SchemaDocument) -> Result<GeneratedFile> {
    let type_name = generated_type_name(schema);
    if !is_csharp_identifier(&type_name) || is_csharp_keyword(&type_name) {
        return Err(MasterdataError::new(
            "E-CODEGEN-INVALID-TYPE-NAME",
            ErrorKind::Validation,
            format!("`{type_name}` is not a valid C# type identifier"),
        ));
    }

    let mut document = CSharpDocument::new();
    document.line("// <auto-generated />");
    document
        .line("// Scaffold only: MasterMemory source generation is intentionally not emitted yet.");
    document.line(format!("// Source table identity: {}", schema.table));
    document.line(format!("// Generated C# type name: {type_name}"));
    document.line("#nullable enable");
    document.line("");
    document.line(format!("namespace {namespace};"));
    document.line("");
    document.line(format!("public sealed partial class {type_name}"));
    document.line("{");
    let mut property_names = BTreeSet::new();
    let mut property_name_keys = BTreeSet::new();
    let mut parameter_names = BTreeSet::new();
    let mut parameter_name_keys = BTreeSet::new();
    for field in &schema.fields {
        let field_name = pascal_case(&field.name);
        if !is_csharp_identifier(&field_name) || is_csharp_keyword(&field_name) {
            return Err(MasterdataError::new(
                "E-CODEGEN-INVALID-PROPERTY-NAME",
                ErrorKind::Validation,
                format!("`{}` is not a valid C# field identifier", field.name),
            ));
        }
        if !property_names.insert(field_name.clone()) {
            return Err(MasterdataError::new(
                "E-CODEGEN-PROPERTY-NAME-COLLISION",
                ErrorKind::Validation,
                format!(
                    "fields in `{}` normalize to the same C# property `{field_name}`",
                    schema.table
                ),
            ));
        }
        if !property_name_keys.insert(field_name.to_ascii_lowercase()) {
            return Err(MasterdataError::new(
                "E-CODEGEN-PROPERTY-NAME-COLLISION",
                ErrorKind::Validation,
                format!(
                    "fields in `{}` normalize to case-insensitively colliding C# properties",
                    schema.table
                ),
            ));
        }
        let parameter_name = camel_case(&field.name);
        if !is_csharp_identifier(&parameter_name) || is_csharp_keyword(&parameter_name) {
            return Err(MasterdataError::new(
                "E-CODEGEN-INVALID-CONSTRUCTOR-PARAMETER",
                ErrorKind::Validation,
                format!(
                    "`{}` does not produce a valid C# constructor parameter",
                    field.name
                ),
            ));
        }
        if !parameter_names.insert(parameter_name.clone()) {
            return Err(MasterdataError::new(
                "E-CODEGEN-CONSTRUCTOR-PARAMETER-COLLISION",
                ErrorKind::Validation,
                format!(
                    "fields in `{}` normalize to the same C# constructor parameter",
                    schema.table
                ),
            ));
        }
        if !parameter_name_keys.insert(parameter_name.to_ascii_lowercase()) {
            return Err(MasterdataError::new(
                "E-CODEGEN-CONSTRUCTOR-PARAMETER-COLLISION",
                ErrorKind::Validation,
                format!(
                    "fields in `{}` normalize to case-insensitively colliding C# constructor parameters",
                    schema.table
                ),
            ));
        }
        document.line(format!(
            "    public {} {field_name} {{ get; }}",
            csharp_type(&field.type_name)?
        ));
    }
    if !schema.fields.is_empty() {
        document.line("");
        document.line(format!("    public {type_name}("));
        for (index, field) in schema.fields.iter().enumerate() {
            let separator = if index + 1 == schema.fields.len() {
                ""
            } else {
                ","
            };
            document.line(format!(
                "        {} {}{}",
                csharp_type(&field.type_name)?,
                camel_case(&field.name),
                separator
            ));
        }
        document.line("    )");
        document.line("    {");
        for field in &schema.fields {
            let field_name = pascal_case(&field.name);
            document.line(format!(
                "        {field_name} = {};",
                camel_case(&field.name)
            ));
        }
        document.line("    }");
    }
    document.line("}");

    Ok(GeneratedFile {
        relative_path: std::path::PathBuf::from(format!("{}.g.cs", type_name)),
        contents: document.finish(),
    })
}

struct CSharpDocument {
    lines: Vec<String>,
}

impl CSharpDocument {
    fn new() -> Self {
        Self { lines: Vec::new() }
    }

    fn line(&mut self, line: impl Into<String>) {
        self.lines.push(line.into());
    }

    fn finish(self) -> String {
        let mut output = self.lines.join("\n");
        output.push('\n');
        output
    }
}

fn csharp_type(type_name: &str) -> Result<&'static str> {
    match type_name {
        "bool" => Ok("bool"),
        "byte" | "uint8" => Ok("byte"),
        "short" | "int16" => Ok("short"),
        "int" | "int32" => Ok("int"),
        "long" | "int64" => Ok("long"),
        "sbyte" => Ok("sbyte"),
        "ushort" | "uint16" => Ok("ushort"),
        "uint" | "uint32" => Ok("uint"),
        "ulong" | "uint64" => Ok("ulong"),
        "float" => Ok("float"),
        "double" => Ok("double"),
        "string" => Ok("string"),
        "" => Err(MasterdataError::new(
            "E-CODEGEN-EMPTY-FIELD-TYPE",
            ErrorKind::Validation,
            "schema field type must not be empty",
        )),
        other => Err(MasterdataError::new(
            "E-CODEGEN-UNSUPPORTED-FIELD-TYPE",
            ErrorKind::NotImplemented,
            format!("custom C# type `{other}` is reserved for a future schema/type generator"),
        )),
    }
}

// Keep this deterministic separator-to-Pascal mapping for the current Table
// scaffold; removing it changes generated Table presentation names and their
// collision checks. Do not reuse it for Value Object or Custom Type names:
// their strict source-name contract rejects implicit repair. Future context
// (the Proposed spec is not current implementation authority):
// docs/specs/type-system/csharp-naming.md (TYPE-NAMING-008) and the generation
// collision tests.
fn pascal_case(value: &str) -> String {
    value
        .split(['-', '_', ' ', '.'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn camel_case(value: &str) -> String {
    let pascal = pascal_case(value);
    let mut chars = pascal.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

fn is_csharp_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    match chars.next() {
        Some(first) if first == '_' || first.is_ascii_alphabetic() => {}
        _ => return false,
    }
    chars.all(|character| character == '_' || character.is_ascii_alphanumeric())
}

fn generated_type_name(schema: &SchemaDocument) -> String {
    schema
        .csharp_name
        .clone()
        .unwrap_or_else(|| pascal_case(&schema.table))
}

fn validate_namespace(namespace: &str) -> Result<()> {
    if namespace.is_empty()
        || namespace
            .split('.')
            .any(|segment| !is_csharp_identifier(segment) || is_csharp_keyword(segment))
    {
        return Err(MasterdataError::new(
            "E-CODEGEN-INVALID-NAMESPACE",
            ErrorKind::Validation,
            format!("`{namespace}` is not a valid C# namespace"),
        ));
    }
    Ok(())
}

fn is_csharp_keyword(value: &str) -> bool {
    matches!(
        value,
        "abstract"
            | "as"
            | "base"
            | "bool"
            | "break"
            | "byte"
            | "case"
            | "catch"
            | "char"
            | "checked"
            | "class"
            | "const"
            | "continue"
            | "decimal"
            | "default"
            | "delegate"
            | "do"
            | "double"
            | "else"
            | "enum"
            | "event"
            | "explicit"
            | "extern"
            | "false"
            | "finally"
            | "fixed"
            | "float"
            | "for"
            | "foreach"
            | "goto"
            | "if"
            | "implicit"
            | "in"
            | "int"
            | "interface"
            | "internal"
            | "is"
            | "lock"
            | "long"
            | "namespace"
            | "new"
            | "null"
            | "object"
            | "operator"
            | "out"
            | "override"
            | "params"
            | "private"
            | "protected"
            | "public"
            | "readonly"
            | "ref"
            | "return"
            | "sbyte"
            | "sealed"
            | "short"
            | "sizeof"
            | "stackalloc"
            | "static"
            | "string"
            | "struct"
            | "switch"
            | "this"
            | "throw"
            | "true"
            | "try"
            | "typeof"
            | "uint"
            | "ulong"
            | "unchecked"
            | "unsafe"
            | "ushort"
            | "using"
            | "virtual"
            | "void"
            | "volatile"
            | "while"
            | "add"
            | "alias"
            | "and"
            | "ascending"
            | "async"
            | "await"
            | "by"
            | "descending"
            | "dynamic"
            | "equals"
            | "file"
            | "from"
            | "get"
            | "global"
            | "group"
            | "init"
            | "into"
            | "join"
            | "let"
            | "managed"
            | "nameof"
            | "nint"
            | "not"
            | "notnull"
            | "on"
            | "or"
            | "orderby"
            | "partial"
            | "record"
            | "remove"
            | "required"
            | "scoped"
            | "select"
            | "set"
            | "unmanaged"
            | "value"
            | "var"
            | "when"
            | "where"
            | "with"
            | "yield"
    )
}

#[allow(dead_code)]
fn _format_note(note: &GenerationNote) -> String {
    let mut text = String::new();
    let _ = write!(&mut text, "{}", note.message);
    text
}
