// <auto-generated />
// Generated by MasterData {{ generator_version }}.
// Source hash: {{ source_hash }}
#nullable enable

using MessagePack;
using System.Collections.Immutable;

namespace {{ namespace }}
{

{body}

}
