// <auto-generated />
// Generated by Lilja.MasterData {{ generator_version }}.
// Source hash: {{ source_hash }}
#nullable enable
#pragma warning disable MsgPack017

using MasterMemory;
using MessagePack;
using System.Collections.Immutable;

namespace {{ namespace }}
{

{body}

}

#pragma warning restore MsgPack017
