//! Shared application workflows for adapters such as the CLI and Tauri GUI.
//!
//! This crate orchestrates project discovery, validation, C# generation, and
//! the .NET boundary. Domain semantics remain in `masterdata-core`, C# syntax
//! remains in `masterdata-codegen-csharp`, and process invocation remains in
//! `masterdata-dotnet`.

use std::collections::BTreeSet;
use std::fs;
use std::io::Read;
use std::path::{Path, PathBuf};

use masterdata_codegen_csharp::{CSharpGenerationPlan, CSharpGenerator};
use masterdata_core::{
    BuildPlan, BuildSelection, ErrorKind, InitOptions, MasterdataError, ProjectInfo,
    ProjectService, Result, ValidationReport,
};
use masterdata_dotnet::{
    BridgeSmokeReport, DotnetBridge, MasterMemoryBuildReport, MasterMemoryBuildRequest,
    MasterMemorySpikeReport,
};
use serde::{Deserialize, Serialize};
use tempfile::TempDir;

const GENERATED_MANIFEST_FILENAME: &str = ".masterdata-generated-files.json";
const GENERATED_HEADER: &[u8] = b"// <auto-generated />";

#[derive(Debug, Clone)]
pub struct ApplicationService {
    project: ProjectService,
    generator: CSharpGenerator,
    dotnet: DotnetBridge,
}

impl Default for ApplicationService {
    fn default() -> Self {
        Self::new()
    }
}

impl ApplicationService {
    pub fn new() -> Self {
        Self {
            project: ProjectService::new(),
            generator: CSharpGenerator::default(),
            dotnet: DotnetBridge::default(),
        }
    }

    /// Construct the shared workflow with an explicit bridge. This is useful
    /// for failure-path tests and keeps process invocation out of CLI/GUI
    /// adapters.
    pub fn with_dotnet(dotnet: DotnetBridge) -> Self {
        Self {
            project: ProjectService::new(),
            generator: CSharpGenerator::default(),
            dotnet,
        }
    }

    pub fn project_info(
        &self,
        explicit_project: Option<&Path>,
        current_dir: &Path,
    ) -> Result<ProjectInfo> {
        self.project.project_info(explicit_project, current_dir)
    }

    pub fn validate(
        &self,
        explicit_project: Option<&Path>,
        current_dir: &Path,
    ) -> Result<ValidationReport> {
        self.project.validate(explicit_project, current_dir)
    }

    pub fn init(&self, root: &Path, options: &InitOptions) -> Result<ProjectInfo> {
        self.project.init(root, options)
    }

    pub fn prepare_build(
        &self,
        explicit_project: Option<&Path>,
        current_dir: &Path,
    ) -> Result<BuildPlan> {
        self.project.prepare_build(explicit_project, current_dir)
    }

    pub fn prepare_build_with_selection(
        &self,
        explicit_project: Option<&Path>,
        current_dir: &Path,
        selection: &BuildSelection,
    ) -> Result<BuildPlan> {
        self.project
            .prepare_build_with_selection(explicit_project, current_dir, selection)
    }

    pub fn plan_csharp(&self, plan: &BuildPlan) -> Result<CSharpGenerationPlan> {
        self.generator.plan(plan)
    }

    /// Run the shared build workflow. `dry_run` stops after planning so that
    /// adapters can inspect the same result without writing or invoking .NET.
    pub fn build(
        &self,
        explicit_project: Option<&Path>,
        current_dir: &Path,
        dry_run: bool,
    ) -> Result<BuildExecution> {
        self.build_with_selection(
            explicit_project,
            current_dir,
            &BuildSelection::unfiltered(),
            dry_run,
        )
    }

    pub fn build_with_selection(
        &self,
        explicit_project: Option<&Path>,
        current_dir: &Path,
        selection: &BuildSelection,
        dry_run: bool,
    ) -> Result<BuildExecution> {
        let plan = self.prepare_build_with_selection(explicit_project, current_dir, selection)?;
        let generation = self.generator.plan(&plan)?;
        let (written_files, binary) = if dry_run {
            (Vec::new(), None)
        } else {
            let final_binary = plan.binary_output.clone().ok_or_else(|| {
                MasterdataError::new(
                    "E-BUILD-BINARY-OUTPUT-NOT-CONFIGURED",
                    ErrorKind::Config,
                    "non-dry-run build requires explicit build.binary_output",
                )
                .with_source(plan.project.config_path.clone())
            })?;
            let binary_parent = final_binary.parent().unwrap_or_else(|| Path::new("."));
            validate_generated_output_location(&plan)?;
            fs::create_dir_all(binary_parent).map_err(|error| {
                MasterdataError::new(
                    "E-BUILD-BINARY-PARENT-CREATE",
                    ErrorKind::Io,
                    format!("could not create binary output directory: {error}"),
                )
                .with_source(binary_parent.to_path_buf())
            })?;

            // WHY: Keep .NET builder intermediates beside the final binary until
            // the real builder and reload validation have succeeded. The
            // generated publication stage is created separately beside its
            // final directory so the directory switch remains same-filesystem
            // even when the two configured outputs use different filesystems.
            // This preserves the previous artifact on any prepare/compile/run
            // failure and gives the final binary rename same-filesystem semantics.
            // EVIDENCE: docs/specs/build-pipeline.md; Regression: unavailable_dotnet_preserves_existing_binary_and_generated_output.
            let workspace_parent = binary_staging_parent(binary_parent, &plan.generated_output);
            fs::create_dir_all(&workspace_parent).map_err(|error| {
                MasterdataError::new(
                    "E-BUILD-STAGING-PARENT-CREATE",
                    ErrorKind::Io,
                    format!("could not create build staging parent: {error}"),
                )
                .with_source(workspace_parent.to_path_buf())
            })?;
            let workspace = TempDir::new_in(&workspace_parent).map_err(|error| {
                MasterdataError::new(
                    "E-BUILD-STAGING-CREATE",
                    ErrorKind::Io,
                    format!("could not create build staging workspace: {error}"),
                )
                .with_source(workspace_parent.to_path_buf())
            })?;
            let staged_generated = workspace.path().join("Generated");
            self.generator.write_to(&generation, &staged_generated)?;
            let staged_binary = workspace.path().join("masterdata.bytes");
            let request =
                MasterMemoryBuildRequest::from_plan(&plan, &generation, staged_binary.clone())?;
            let mut report =
                self.dotnet
                    .build_mastermemory(&request, &staged_generated, workspace.path())?;

            let generated_parent = plan
                .generated_output
                .parent()
                .unwrap_or_else(|| Path::new("."));
            fs::create_dir_all(generated_parent).map_err(|error| {
                MasterdataError::new(
                    "E-BUILD-GENERATED-PUBLISH",
                    ErrorKind::Io,
                    format!("could not create generated output parent: {error}"),
                )
                .with_source(generated_parent.to_path_buf())
            })?;
            let generated_staging = TempDir::new_in(generated_parent).map_err(|error| {
                MasterdataError::new(
                    "E-BUILD-GENERATED-PUBLISH",
                    ErrorKind::Io,
                    format!("could not create generated publication staging: {error}"),
                )
                .with_source(generated_parent.to_path_buf())
            })?;
            let staged_publication_generated = generated_staging.path().join("Generated");
            materialize_generated_output(
                &self.generator,
                &generation,
                &plan.generated_output,
                &staged_publication_generated,
            )?;

            // WHY: Both final artifacts are prepared before publication. The
            // generated directory is switched as a complete set first; if the
            // subsequent binary replacement fails, the publication state
            // restores the previous generated directory before returning Err.
            // This prevents an ordinary I/O failure from exposing a NEW/OLD
            // artifact pair while avoiding a claim of crash-time
            // cross-filesystem atomicity.
            // EVIDENCE: docs/specs/build-pipeline.md; Regression: binary_publication_failure_rolls_back_generated_output.
            publish_artifacts(
                &staged_binary,
                &final_binary,
                &staged_publication_generated,
                &plan.generated_output,
            )?;
            report.binary_path = final_binary;
            let written_files = generation
                .files
                .iter()
                .map(|file| plan.generated_output.join(&file.relative_path))
                .collect();
            (written_files, Some(report))
        };
        Ok(BuildExecution {
            plan,
            generation,
            written_files,
            binary,
        })
    }

    pub fn bridge_smoke_test(&self, repository_root: &Path) -> Result<BridgeSmokeReport> {
        self.dotnet.smoke_test(repository_root)
    }

    pub fn mastermemory_spike(&self, repository_root: &Path) -> Result<MasterMemorySpikeReport> {
        self.dotnet.mastermemory_spike(repository_root)
    }
}

#[derive(Debug, Clone)]
pub struct BuildExecution {
    pub plan: BuildPlan,
    pub generation: CSharpGenerationPlan,
    pub written_files: Vec<PathBuf>,
    pub binary: Option<MasterMemoryBuildReport>,
}

#[derive(Debug, Deserialize, Serialize)]
struct GeneratedManifest {
    version: u32,
    files: Vec<String>,
}

const GENERATED_MANIFEST_VERSION: u32 = 1;

/// Choose a binary staging parent that remains reachable if the generated
/// output directory is later switched as a whole. The normal configuration
/// uses sibling directories, but this also keeps the staging file alive when
/// a caller deliberately places the binary below the generated directory.
fn binary_staging_parent(binary_parent: &Path, generated_output: &Path) -> PathBuf {
    if is_path_ancestor_or_equal(generated_output, binary_parent) {
        generated_output
            .parent()
            .unwrap_or_else(|| Path::new("."))
            .to_path_buf()
    } else {
        binary_parent.to_path_buf()
    }
}

fn validate_generated_output_location(plan: &BuildPlan) -> Result<()> {
    let generated_output = &plan.generated_output;
    let project_root = &plan.project.project_root;
    if is_path_ancestor_or_equal(generated_output, project_root)
        || plan
            .project
            .source_roots
            .iter()
            .any(|source_root| is_path_ancestor_or_equal(generated_output, source_root))
    {
        return Err(MasterdataError::new(
            "E-BUILD-GENERATED-PUBLISH",
            ErrorKind::Config,
            "generated output must not replace the project root or a configured source root",
        )
        .with_source(generated_output.clone()));
    }
    Ok(())
}

fn is_path_ancestor_or_equal(candidate: &Path, target: &Path) -> bool {
    normalize_path(candidate) == normalize_path(target)
        || normalize_path(target).starts_with(normalize_path(candidate))
}

fn normalize_path(path: &Path) -> PathBuf {
    let mut normalized = PathBuf::new();
    for component in path.components() {
        match component {
            std::path::Component::Prefix(prefix) => normalized.push(prefix.as_os_str()),
            std::path::Component::RootDir => normalized.push(component.as_os_str()),
            std::path::Component::CurDir => {}
            std::path::Component::ParentDir => {
                normalized.pop();
            }
            std::path::Component::Normal(part) => normalized.push(part),
        }
    }
    normalized
}

fn generated_publish_error(path: &Path, message: impl Into<String>) -> MasterdataError {
    MasterdataError::new("E-BUILD-GENERATED-PUBLISH", ErrorKind::Io, message).with_source(path)
}

fn generated_path_key(path: &Path) -> Result<String> {
    if path.as_os_str().is_empty() || path.is_absolute() {
        return Err(generated_publish_error(
            path,
            "generated manifest contains an unsafe path",
        ));
    }
    let mut components = Vec::new();
    for component in path.components() {
        match component {
            std::path::Component::Normal(part) => {
                let part = part.to_str().ok_or_else(|| {
                    generated_publish_error(path, "generated manifest path is not valid Unicode")
                })?;
                if part.is_empty() || part.contains(['/', '\\']) {
                    return Err(generated_publish_error(
                        path,
                        "generated manifest contains an unsafe path component",
                    ));
                }
                components.push(part.to_owned());
            }
            std::path::Component::CurDir => {}
            std::path::Component::Prefix(_)
            | std::path::Component::RootDir
            | std::path::Component::ParentDir => {
                return Err(generated_publish_error(
                    path,
                    "generated manifest contains an unsafe path",
                ));
            }
        }
    }
    if components.is_empty() {
        return Err(generated_publish_error(
            path,
            "generated manifest contains an empty path",
        ));
    }
    Ok(components.join("/"))
}

fn read_managed_generated_paths(output_dir: &Path) -> Result<BTreeSet<String>> {
    let metadata = match fs::symlink_metadata(output_dir) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            return Ok(BTreeSet::new());
        }
        Err(error) => {
            return Err(generated_publish_error(
                output_dir,
                format!("could not inspect existing generated output: {error}"),
            ));
        }
    };
    if !metadata.file_type().is_dir() || metadata.file_type().is_symlink() {
        return Err(generated_publish_error(
            output_dir,
            "existing generated output is not a real directory",
        ));
    }

    let manifest_path = output_dir.join(GENERATED_MANIFEST_FILENAME);
    let manifest_metadata = match fs::symlink_metadata(&manifest_path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            return discover_legacy_generated_paths(output_dir);
        }
        Err(error) => {
            return Err(generated_publish_error(
                &manifest_path,
                format!("could not inspect generated output manifest: {error}"),
            ));
        }
    };
    if !manifest_metadata.file_type().is_file() || manifest_metadata.file_type().is_symlink() {
        return Err(generated_publish_error(
            &manifest_path,
            "generated output manifest is not a regular file",
        ));
    }
    let content = fs::read_to_string(&manifest_path).map_err(|error| {
        generated_publish_error(
            &manifest_path,
            format!("could not read generated output manifest: {error}"),
        )
    })?;
    let manifest: GeneratedManifest = serde_json::from_str(&content).map_err(|error| {
        generated_publish_error(
            &manifest_path,
            format!("could not parse generated output manifest: {error}"),
        )
    })?;
    if manifest.version != GENERATED_MANIFEST_VERSION {
        return Err(generated_publish_error(
            &manifest_path,
            format!(
                "unsupported generated output manifest version {}",
                manifest.version
            ),
        ));
    }
    let mut managed = BTreeSet::new();
    for path in manifest.files {
        let key = generated_path_key(Path::new(&path))?;
        if !managed.insert(key) {
            return Err(generated_publish_error(
                &manifest_path,
                "generated output manifest contains duplicate paths",
            ));
        }
        let managed_path = output_dir.join(&path);
        match fs::symlink_metadata(&managed_path) {
            Ok(metadata)
                if !metadata.file_type().is_file() || metadata.file_type().is_symlink() =>
            {
                return Err(generated_publish_error(
                    &managed_path,
                    "generated output manifest points to a non-file entry",
                ));
            }
            Ok(_) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => {
                return Err(generated_publish_error(
                    &managed_path,
                    format!("could not inspect managed generated file: {error}"),
                ));
            }
        }
    }
    Ok(managed)
}

fn discover_legacy_generated_paths(output_dir: &Path) -> Result<BTreeSet<String>> {
    let mut managed = BTreeSet::new();
    discover_legacy_generated_paths_recursive(output_dir, Path::new(""), &mut managed)?;
    Ok(managed)
}

fn discover_legacy_generated_paths_recursive(
    directory: &Path,
    relative_directory: &Path,
    managed: &mut BTreeSet<String>,
) -> Result<()> {
    for entry in fs::read_dir(directory).map_err(|error| {
        generated_publish_error(
            directory,
            format!("could not inspect existing generated output: {error}"),
        )
    })? {
        let entry = entry.map_err(|error| {
            generated_publish_error(
                directory,
                format!("could not inspect existing generated output entry: {error}"),
            )
        })?;
        let source = entry.path();
        let relative = relative_directory.join(entry.file_name());
        let file_type = entry.file_type().map_err(|error| {
            generated_publish_error(
                &source,
                format!("could not inspect generated output entry: {error}"),
            )
        })?;
        if file_type.is_symlink() {
            continue;
        }
        if file_type.is_dir() {
            discover_legacy_generated_paths_recursive(&source, &relative, managed)?;
        } else if file_type.is_file() && has_generated_header(&source)? {
            managed.insert(generated_path_key(&relative)?);
        }
    }
    Ok(())
}

fn has_generated_header(path: &Path) -> Result<bool> {
    let mut file = fs::File::open(path).map_err(|error| {
        generated_publish_error(
            path,
            format!("could not inspect existing generated file: {error}"),
        )
    })?;
    let mut prefix = vec![0; GENERATED_HEADER.len()];
    let length = file.read(&mut prefix).map_err(|error| {
        generated_publish_error(
            path,
            format!("could not inspect existing generated file: {error}"),
        )
    })?;
    Ok(prefix[..length] == *GENERATED_HEADER)
}

fn materialize_generated_output(
    generator: &CSharpGenerator,
    plan: &CSharpGenerationPlan,
    final_output: &Path,
    staged_output: &Path,
) -> Result<()> {
    // WHY: build.output has no product-level whole-directory ownership rule.
    // The manifest and existing auto-generated header identify files this
    // publisher may retire; every other regular entry is copied into the new
    // set so a directory switch cannot silently delete user-owned content.
    // IF REMOVED: stale generated files would survive, or directory replacement
    // could destroy files that this tool does not own.
    // EVIDENCE: docs/specs/build-pipeline.md; Regression: materialized_generated_set_removes_stale_legacy_files_and_preserves_user_files.
    let managed = read_managed_generated_paths(final_output)?;
    fs::create_dir_all(staged_output).map_err(|error| {
        generated_publish_error(
            staged_output,
            format!("could not create generated publication staging: {error}"),
        )
    })?;
    if final_output.exists() {
        copy_unmanaged_output(final_output, staged_output, &managed)?;
    }
    generator.write_to(plan, staged_output)?;

    let mut files = BTreeSet::new();
    for file in &plan.files {
        files.insert(generated_path_key(&file.relative_path)?);
    }
    if files.len() != plan.files.len() {
        return Err(generated_publish_error(
            staged_output,
            "generated C# plan contains duplicate relative paths",
        ));
    }
    let manifest = GeneratedManifest {
        version: GENERATED_MANIFEST_VERSION,
        files: files.into_iter().collect(),
    };
    let manifest_path = staged_output.join(GENERATED_MANIFEST_FILENAME);
    let content = serde_json::to_vec_pretty(&manifest).map_err(|error| {
        generated_publish_error(
            &manifest_path,
            format!("could not serialize generated output manifest: {error}"),
        )
    })?;
    fs::write(&manifest_path, content).map_err(|error| {
        generated_publish_error(
            &manifest_path,
            format!("could not write generated output manifest: {error}"),
        )
    })?;
    Ok(())
}

fn copy_unmanaged_output(
    source_dir: &Path,
    destination_dir: &Path,
    managed: &BTreeSet<String>,
) -> Result<()> {
    for entry in fs::read_dir(source_dir).map_err(|error| {
        generated_publish_error(
            source_dir,
            format!("could not inspect existing generated output: {error}"),
        )
    })? {
        let entry = entry.map_err(|error| {
            generated_publish_error(
                source_dir,
                format!("could not inspect existing generated output entry: {error}"),
            )
        })?;
        let name = entry.file_name();
        if name == GENERATED_MANIFEST_FILENAME {
            continue;
        }
        let relative = PathBuf::from(&name);
        copy_unmanaged_entry(
            &entry.path(),
            &destination_dir.join(&name),
            &relative,
            managed,
        )?;
    }
    Ok(())
}

fn copy_unmanaged_entry(
    source: &Path,
    destination: &Path,
    relative: &Path,
    managed: &BTreeSet<String>,
) -> Result<()> {
    let key = generated_path_key(relative)?;
    if managed.contains(&key) {
        return Ok(());
    }
    let file_type = fs::symlink_metadata(source)
        .map_err(|error| {
            generated_publish_error(source, format!("could not inspect output: {error}"))
        })?
        .file_type();
    if file_type.is_symlink() {
        return Err(generated_publish_error(
            source,
            "symlink entries in generated output cannot be safely published",
        ));
    }
    if file_type.is_dir() {
        fs::create_dir_all(destination).map_err(|error| {
            generated_publish_error(
                destination,
                format!("could not stage generated output directory: {error}"),
            )
        })?;
        for entry in fs::read_dir(source).map_err(|error| {
            generated_publish_error(
                source,
                format!("could not inspect generated output directory: {error}"),
            )
        })? {
            let entry = entry.map_err(|error| {
                generated_publish_error(
                    source,
                    format!("could not inspect generated output entry: {error}"),
                )
            })?;
            let child_name = entry.file_name();
            let child_relative = relative.join(&child_name);
            copy_unmanaged_entry(
                &entry.path(),
                &destination.join(&child_name),
                &child_relative,
                managed,
            )?;
        }
    } else if file_type.is_file() {
        fs::copy(source, destination).map_err(|error| {
            generated_publish_error(
                destination,
                format!("could not stage generated output file: {error}"),
            )
        })?;
    } else {
        return Err(generated_publish_error(
            source,
            "generated output contains an unsupported filesystem entry",
        ));
    }
    Ok(())
}

struct GeneratedPublication {
    final_path: PathBuf,
    previous_path: Option<PathBuf>,
    backup_root: TempDir,
}

fn publish_generated_directory(staged: &Path, final_path: &Path) -> Result<GeneratedPublication> {
    let staged_metadata = fs::symlink_metadata(staged).map_err(|error| {
        generated_publish_error(
            staged,
            format!("could not inspect staged generated output: {error}"),
        )
    })?;
    if !staged_metadata.file_type().is_dir() || staged_metadata.file_type().is_symlink() {
        return Err(generated_publish_error(
            staged,
            "staged generated output is not a real directory",
        ));
    }
    let parent = final_path.parent().unwrap_or_else(|| Path::new("."));
    let backup_root = TempDir::new_in(parent).map_err(|error| {
        generated_publish_error(
            parent,
            format!("could not create generated publication rollback area: {error}"),
        )
    })?;
    let previous_path = backup_root.path().join("previous");
    let final_metadata = match fs::symlink_metadata(final_path) {
        Ok(metadata) => Some(metadata),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => None,
        Err(error) => {
            return Err(generated_publish_error(
                final_path,
                format!("could not inspect generated output: {error}"),
            ));
        }
    };
    if let Some(metadata) = &final_metadata
        && (!metadata.file_type().is_dir() || metadata.file_type().is_symlink())
    {
        return Err(generated_publish_error(
            final_path,
            "existing generated output is not a real directory",
        ));
    }
    if final_metadata.is_some() {
        fs::rename(final_path, &previous_path).map_err(|error| {
            generated_publish_error(
                final_path,
                format!("could not stage previous generated output for replacement: {error}"),
            )
        })?;
    }
    if let Err(error) = fs::rename(staged, final_path) {
        let publication_error = generated_publish_error(
            final_path,
            format!("could not publish generated output directory: {error}"),
        );
        if final_metadata.is_some()
            && let Err(restore_error) = fs::rename(&previous_path, final_path)
        {
            let retained = backup_root.keep();
            return Err(combine_publication_errors(
                publication_error,
                generated_publish_error(
                    &retained,
                    format!(
                        "could not restore previous generated output: {restore_error}; rollback area retained"
                    ),
                ),
                final_path,
            ));
        }
        return Err(publication_error);
    }
    Ok(GeneratedPublication {
        final_path: final_path.to_path_buf(),
        previous_path: final_metadata.map(|_| previous_path),
        backup_root,
    })
}

fn publish_artifacts(
    staged_binary: &Path,
    final_binary: &Path,
    staged_generated: &Path,
    final_generated: &Path,
) -> Result<()> {
    let generated_publication = publish_generated_directory(staged_generated, final_generated)?;
    if let Err(binary_error) = atomic_replace(staged_binary, final_binary) {
        if let Err(rollback_error) = generated_publication.rollback() {
            return Err(combine_publication_errors(
                binary_error,
                rollback_error,
                final_generated,
            ));
        }
        return Err(binary_error);
    }
    generated_publication.commit();
    Ok(())
}

impl GeneratedPublication {
    fn commit(self) {}

    fn rollback(self) -> Result<()> {
        let GeneratedPublication {
            final_path,
            previous_path,
            backup_root,
        } = self;
        let discarded_path = backup_root.path().join("published");
        if let Err(error) = move_if_present(&final_path, &discarded_path) {
            let retained = backup_root.keep();
            return Err(MasterdataError::new(
                "E-BUILD-ARTIFACT-ROLLBACK",
                ErrorKind::Io,
                format!(
                    "could not move published generated output during rollback: {error}; rollback area retained at {}",
                    retained.display()
                ),
            )
            .with_source(final_path));
        }
        if let Some(previous_path) = previous_path
            && let Err(error) = fs::rename(&previous_path, &final_path)
        {
            let retained = backup_root.keep();
            return Err(MasterdataError::new(
                "E-BUILD-ARTIFACT-ROLLBACK",
                ErrorKind::Io,
                format!(
                    "could not restore previous generated output during rollback: {error}; rollback area retained at {}",
                    retained.display()
                ),
            )
            .with_source(final_path));
        }
        Ok(())
    }
}

fn move_if_present(source: &Path, destination: &Path) -> std::io::Result<()> {
    match fs::symlink_metadata(source) {
        Ok(_) => fs::rename(source, destination),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error),
    }
}

fn combine_publication_errors(
    original: MasterdataError,
    rollback: MasterdataError,
    source: &Path,
) -> MasterdataError {
    MasterdataError::new(
        "E-BUILD-ARTIFACT-ROLLBACK",
        ErrorKind::Io,
        format!(
            "artifact publication failed [{}]: {}; rollback failed [{}]: {}",
            original.diagnostic().code,
            original.diagnostic().message,
            rollback.diagnostic().code,
            rollback.diagnostic().message,
        ),
    )
    .with_source(source.to_path_buf())
}

fn atomic_replace(staged: &Path, final_path: &Path) -> Result<()> {
    if !staged.is_file() {
        return Err(MasterdataError::new(
            "E-BUILD-BINARY-PUBLISH",
            ErrorKind::Io,
            "staged binary is missing",
        )
        .with_source(staged.to_path_buf()));
    }

    #[cfg(windows)]
    {
        atomic_replace_windows(staged, final_path)
    }
    #[cfg(not(windows))]
    {
        fs::rename(staged, final_path).map_err(|error| {
            MasterdataError::new(
                "E-BUILD-BINARY-PUBLISH",
                ErrorKind::Io,
                format!("could not atomically publish binary: {error}"),
            )
            .with_source(final_path.to_path_buf())
        })
    }
}

#[cfg(windows)]
fn atomic_replace_windows(staged: &Path, final_path: &Path) -> Result<()> {
    use std::ffi::c_void;
    use std::os::windows::ffi::OsStrExt;

    const REPLACEFILE_WRITE_THROUGH: u32 = 0x00000001;
    const MOVEFILE_WRITE_THROUGH: u32 = 0x00000008;

    unsafe extern "system" {
        fn MoveFileExW(existing: *const u16, new: *const u16, flags: u32) -> i32;
        fn ReplaceFileW(
            replaced: *const u16,
            replacement: *const u16,
            backup: *const u16,
            flags: u32,
            exclude: *mut c_void,
            reserved: *mut c_void,
        ) -> i32;
    }

    fn wide(path: &Path) -> Vec<u16> {
        path.as_os_str()
            .encode_wide()
            .chain(std::iter::once(0))
            .collect()
    }

    let staged = wide(staged);
    let final_path_wide = wide(final_path);
    let success = unsafe {
        if final_path.exists() {
            ReplaceFileW(
                final_path_wide.as_ptr(),
                staged.as_ptr(),
                std::ptr::null(),
                REPLACEFILE_WRITE_THROUGH,
                std::ptr::null_mut(),
                std::ptr::null_mut(),
            ) != 0
        } else {
            MoveFileExW(
                staged.as_ptr(),
                final_path_wide.as_ptr(),
                MOVEFILE_WRITE_THROUGH,
            ) != 0
        }
    };
    if success {
        Ok(())
    } else {
        Err(MasterdataError::new(
            "E-BUILD-BINARY-PUBLISH",
            ErrorKind::Io,
            format!(
                "could not atomically publish binary: {}",
                std::io::Error::last_os_error()
            ),
        )
        .with_source(final_path.to_path_buf()))
    }
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::{Path, PathBuf};

    use masterdata_codegen_csharp::GeneratedFile;
    use tempfile::tempdir;

    use super::{
        ApplicationService, CSharpGenerationPlan, CSharpGenerator, GENERATED_MANIFEST_FILENAME,
        GENERATED_MANIFEST_VERSION, GeneratedManifest, atomic_replace,
        materialize_generated_output, publish_artifacts, publish_generated_directory,
    };
    use masterdata_core::PROJECT_CONFIG_FILENAME;
    use masterdata_dotnet::DotnetBridge;

    #[test]
    fn missing_binary_output_is_rejected_without_writing_generated_output() {
        let directory = tempdir().expect("temporary directory");
        fs::create_dir(directory.path().join("sources")).expect("sources");
        fs::write(
            directory.path().join(PROJECT_CONFIG_FILENAME),
            "[project]\nid = \"build.test\"\nname = \"Build Test\"\nversion = \"0.1.0\"\n",
        )
        .expect("config");
        fs::write(
            directory.path().join("sources/item.yaml"),
            "kind: schema\ntable: item\nfields:\n  - key: 0\n    name: id\n    type: int\nprimaryKey:\n  fields: [id]\n",
        )
        .expect("schema");

        let error = ApplicationService::new()
            .build(Some(directory.path()), directory.path(), false)
            .expect_err("binary output configuration");

        assert_eq!(
            error.diagnostic().code,
            "E-BUILD-BINARY-OUTPUT-NOT-CONFIGURED"
        );
        assert!(!directory.path().join(".masterdata/generated").exists());
    }

    #[test]
    fn unavailable_dotnet_preserves_existing_binary_and_generated_output() {
        let directory = test_project("binary_output = \".masterdata/output/masterdata.bytes\"\n");
        let binary_path = directory.path().join(".masterdata/output/masterdata.bytes");
        let generated_path = directory.path().join(".masterdata/generated/old.g.cs");
        fs::create_dir_all(binary_path.parent().expect("binary parent")).expect("binary parent");
        fs::create_dir_all(generated_path.parent().expect("generated parent"))
            .expect("generated parent");
        fs::write(&binary_path, b"OLD-BINARY").expect("old binary");
        fs::write(&generated_path, b"OLD-GENERATED").expect("old generated output");

        let service = ApplicationService::with_dotnet(DotnetBridge::with_executable(
            "/definitely/missing/masterdata-dotnet",
        ));
        let error = service
            .build(Some(directory.path()), directory.path(), false)
            .expect_err("missing dotnet SDK");

        assert_eq!(error.diagnostic().code, "E-DOTNET-SDK-UNAVAILABLE");
        assert_eq!(fs::read(&binary_path).expect("binary"), b"OLD-BINARY");
        assert_eq!(
            fs::read(&generated_path).expect("generated"),
            b"OLD-GENERATED"
        );
    }

    #[test]
    fn missing_builder_preserves_existing_binary_and_generated_output() {
        let directory = test_project("binary_output = \".masterdata/output/masterdata.bytes\"\n");
        let binary_path = directory.path().join(".masterdata/output/masterdata.bytes");
        let generated_path = directory.path().join(".masterdata/generated/old.g.cs");
        fs::create_dir_all(binary_path.parent().expect("binary parent")).expect("binary parent");
        fs::create_dir_all(generated_path.parent().expect("generated parent"))
            .expect("generated parent");
        fs::write(&binary_path, b"OLD-BINARY").expect("old binary");
        fs::write(&generated_path, b"OLD-GENERATED").expect("old generated output");

        let service = ApplicationService::with_dotnet(
            DotnetBridge::new().with_repository_root(directory.path()),
        );
        let error = service
            .build(Some(directory.path()), directory.path(), false)
            .expect_err("missing builder project");

        assert_eq!(error.diagnostic().code, "E-DOTNET-BUILDER-MISSING");
        assert_eq!(fs::read(&binary_path).expect("binary"), b"OLD-BINARY");
        assert_eq!(
            fs::read(&generated_path).expect("generated"),
            b"OLD-GENERATED"
        );
    }

    #[test]
    fn atomic_replace_publishes_when_final_is_absent_or_existing() {
        let directory = tempdir().expect("temporary directory");
        let staged = directory.path().join("staged.bytes");
        let final_path = directory.path().join("output.bytes");
        fs::write(&staged, b"NEW").expect("staged");
        atomic_replace(&staged, &final_path).expect("first publish");
        assert_eq!(fs::read(&final_path).expect("final"), b"NEW");

        let staged = directory.path().join("staged-again.bytes");
        fs::write(&staged, b"NEWER").expect("staged again");
        atomic_replace(&staged, &final_path).expect("replacement publish");
        assert_eq!(fs::read(&final_path).expect("final"), b"NEWER");
        assert!(!staged.exists());
    }

    #[test]
    fn atomic_replace_rejects_missing_staged_file() {
        let directory = tempdir().expect("temporary directory");
        let error = atomic_replace(
            &directory.path().join("missing.bytes"),
            &directory.path().join("output.bytes"),
        )
        .expect_err("missing staged file");
        assert_eq!(error.diagnostic().code, "E-BUILD-BINARY-PUBLISH");
    }

    #[test]
    fn generated_publication_failure_preserves_existing_artifact_pair() {
        let directory = tempdir().expect("temporary directory");
        let generated = directory.path().join("Generated");
        let binary = directory.path().join("masterdata.bytes");
        fs::create_dir_all(&generated).expect("generated");
        fs::write(generated.join("Old.g.cs"), b"OLD-GENERATED").expect("old generated");
        write_manifest(&generated, &["Old.g.cs"]);
        fs::write(&binary, b"OLD-BINARY").expect("old binary");
        let staged_binary = directory.path().join("staged.bytes");
        fs::write(&staged_binary, b"NEW-BINARY").expect("staged binary");

        let error = publish_artifacts(
            &staged_binary,
            &binary,
            &directory.path().join("missing-generated"),
            &generated,
        )
        .expect_err("generated publication failure");

        assert_eq!(error.diagnostic().code, "E-BUILD-GENERATED-PUBLISH");
        assert_eq!(fs::read(&binary).expect("binary"), b"OLD-BINARY");
        assert_eq!(
            fs::read(generated.join("Old.g.cs")).expect("generated"),
            b"OLD-GENERATED"
        );
        assert!(
            staged_binary.is_file(),
            "failed publication keeps staging for cleanup"
        );
    }

    #[test]
    fn binary_publication_failure_rolls_back_generated_output() {
        let directory = tempdir().expect("temporary directory");
        let generated = directory.path().join("Generated");
        let binary = directory.path().join("masterdata.bytes");
        let staged_generated = directory.path().join("staged-generated");
        fs::create_dir_all(&generated).expect("generated");
        fs::write(generated.join("Old.g.cs"), b"OLD-GENERATED").expect("old generated");
        write_manifest(&generated, &["Old.g.cs"]);
        fs::write(&binary, b"OLD-BINARY").expect("old binary");
        fs::create_dir_all(&staged_generated).expect("staged generated");
        fs::write(staged_generated.join("New.g.cs"), b"NEW-GENERATED").expect("new generated");
        write_manifest(&staged_generated, &["New.g.cs"]);

        let error = publish_artifacts(
            &directory.path().join("missing-staged.bytes"),
            &binary,
            &staged_generated,
            &generated,
        )
        .expect_err("binary publication failure");

        assert_eq!(error.diagnostic().code, "E-BUILD-BINARY-PUBLISH");
        assert_eq!(fs::read(&binary).expect("binary"), b"OLD-BINARY");
        assert_eq!(
            fs::read(generated.join("Old.g.cs")).expect("old generated"),
            b"OLD-GENERATED"
        );
        assert!(!generated.join("New.g.cs").exists());
        let manifest =
            fs::read_to_string(generated.join(GENERATED_MANIFEST_FILENAME)).expect("manifest");
        assert!(manifest.contains("Old.g.cs"));
        assert!(!manifest.contains("New.g.cs"));
    }

    #[test]
    fn first_publication_failure_does_not_leave_new_generated_output() {
        let directory = tempdir().expect("temporary directory");
        let generated = directory.path().join("Generated");
        let binary = directory.path().join("masterdata.bytes");
        let staged_generated = directory.path().join("staged-generated");
        fs::create_dir_all(&staged_generated).expect("staged generated");
        fs::write(staged_generated.join("New.g.cs"), b"NEW-GENERATED").expect("new generated");
        write_manifest(&staged_generated, &["New.g.cs"]);

        let error = publish_artifacts(
            &directory.path().join("missing-staged.bytes"),
            &binary,
            &staged_generated,
            &generated,
        )
        .expect_err("binary publication failure");

        assert_eq!(error.diagnostic().code, "E-BUILD-BINARY-PUBLISH");
        assert!(!binary.exists());
        assert!(!generated.exists());
    }

    #[test]
    fn materialized_generated_set_removes_stale_legacy_files_and_preserves_user_files() {
        let directory = tempdir().expect("temporary directory");
        let generated = directory.path().join("Generated");
        let staged = directory.path().join("staged-generated");
        fs::create_dir_all(&generated).expect("generated");
        fs::write(generated.join("A.g.cs"), b"// <auto-generated />\nOLD-A").expect("old A");
        fs::write(generated.join("B.g.cs"), b"// <auto-generated />\nOLD-B").expect("old B");
        fs::write(generated.join("UserNotes.txt"), b"KEEP-ME").expect("user file");

        let plan = generation_plan(&[("A.g.cs", "// <auto-generated />\nNEW-A")]);
        materialize_generated_output(&CSharpGenerator::default(), &plan, &generated, &staged)
            .expect("materialize generated output");
        let publication = publish_generated_directory(&staged, &generated).expect("publish");
        publication.commit();

        assert_eq!(
            fs::read(generated.join("A.g.cs")).expect("new A"),
            b"// <auto-generated />\nNEW-A"
        );
        assert!(!generated.join("B.g.cs").exists());
        assert_eq!(
            fs::read(generated.join("UserNotes.txt")).expect("user file"),
            b"KEEP-ME"
        );
    }

    #[test]
    fn materialized_generated_set_removes_renamed_manifest_file() {
        let directory = tempdir().expect("temporary directory");
        let generated = directory.path().join("Generated");
        let staged = directory.path().join("staged-generated");
        fs::create_dir_all(&generated).expect("generated");
        fs::write(generated.join("OldName.g.cs"), b"OLD").expect("old generated");
        write_manifest(&generated, &["OldName.g.cs"]);

        let plan = generation_plan(&[("NewName.g.cs", "// <auto-generated />\nNEW")]);
        materialize_generated_output(&CSharpGenerator::default(), &plan, &generated, &staged)
            .expect("materialize generated output");
        let publication = publish_generated_directory(&staged, &generated).expect("publish");
        publication.commit();

        assert!(!generated.join("OldName.g.cs").exists());
        assert_eq!(
            fs::read(generated.join("NewName.g.cs")).expect("new generated"),
            b"// <auto-generated />\nNEW"
        );
    }

    #[test]
    fn binary_staging_moves_outside_generated_output_when_binary_is_nested() {
        let binary_parent = Path::new("project/generated").join("output");
        let generated_output = Path::new("project/generated");
        assert_eq!(
            super::binary_staging_parent(&binary_parent, generated_output),
            PathBuf::from("project")
        );
    }

    fn generation_plan(files: &[(&str, &str)]) -> CSharpGenerationPlan {
        CSharpGenerationPlan {
            namespace: "Masterdata.Generated".to_owned(),
            files: files
                .iter()
                .map(|(path, contents)| GeneratedFile {
                    relative_path: PathBuf::from(path),
                    contents: (*contents).to_owned(),
                })
                .collect(),
            notes: Vec::new(),
        }
    }

    fn write_manifest(directory: &Path, files: &[&str]) {
        let manifest = GeneratedManifest {
            version: GENERATED_MANIFEST_VERSION,
            files: files.iter().map(|file| (*file).to_owned()).collect(),
        };
        fs::write(
            directory.join(GENERATED_MANIFEST_FILENAME),
            serde_json::to_vec(&manifest).expect("manifest JSON"),
        )
        .expect("manifest");
    }

    fn test_project(build: &str) -> tempfile::TempDir {
        let directory = tempdir().expect("temporary directory");
        fs::create_dir(directory.path().join("sources")).expect("sources");
        fs::write(
            directory.path().join(PROJECT_CONFIG_FILENAME),
            format!(
                "[project]\nid = \"build.test\"\nname = \"Build Test\"\nversion = \"0.1.0\"\n\n[build]\n{build}"
            ),
        )
        .expect("config");
        fs::write(
            directory.path().join("sources/item.yaml"),
            "kind: schema\ntable: item\nfields:\n  - key: 0\n    name: id\n    type: int\nprimaryKey:\n  fields: [id]\n",
        )
        .expect("schema");
        directory
    }
}
