//! Deterministic C# lowering of the shared resolved model. MessagePack and
//! MasterMemory execution stay in the native .NET boundary, not this module.
use crate::{
    Error, Result,
    project::Project,
    semantic::{self, Field, Table, Type},
};
use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write,
};

const PREFIX: &str = "// Generated by MasterData.\n#nullable enable\n";
fn invalid(message: impl Into<String>) -> Error {
    Error::new("E-CODEGEN", message)
}
pub fn field_type(field: &Field) -> String {
    let base = base_type(&field.type_name);
    if field.array {
        format!("global::System.Collections.Immutable.ImmutableArray<{base}>")
    } else if field.nullable {
        format!("{base}?")
    } else {
        base
    }
}
fn base_type(name: &str) -> String {
    if semantic::primitive(name) {
        name.into()
    } else {
        format!("global::Masterdata.Generated.{name}")
    }
}
fn check_fields(fields: &[Field]) -> Result<()> {
    // KeyAttribute takes an Int32 and ReadArrayHeader returns an Int32 length.
    // This is the native backend's range, not a source identity/allocation rule.
    if fields.iter().any(|field| field.key >= i32::MAX as u32) {
        return Err(invalid(
            "MessagePack field key is outside the native backend's representable layout",
        ));
    }
    Ok(())
}
pub fn generate(project: &Project) -> Result<BTreeMap<String, String>> {
    let mut names = BTreeSet::from([
        "MemoryDatabase".to_owned(),
        "DatabaseBuilder".into(),
        "ImmutableBuilder".into(),
        "MasterMemoryResolver".into(),
        "MemoryTable".into(),
        "PrimaryKey".into(),
        "SecondaryKey".into(),
        "NonUnique".into(),
    ]);
    for name in project
        .types
        .keys()
        .chain(project.tables.values().map(|table| &table.csharp_name))
    {
        if !names.insert(name.clone()) {
            return Err(invalid(format!("{name}: generated type collision")));
        }
    }
    let mut files = BTreeMap::new();
    let filename = |name: &str| {
        let alias = names
            .iter()
            .filter(|other| other.eq_ignore_ascii_case(name))
            .count()
            > 1;
        if alias || name.len() > 200 {
            // Identifiers remain exact. Output filenames have no public naming
            // contract; distinct valid identifiers must also compile on a
            // case-insensitive filesystem without silently replacing a file.
            format!(
                "{}-{}.g.cs",
                &name[..name.len().min(120)],
                crate::source::content_identity(name.as_bytes())
            )
        } else {
            format!("{name}.g.cs")
        }
    };
    for (name, declaration) in project.types.iter() {
        let body = match declaration {
            Type::ValueObject {
                underlying,
                from_implicit,
                to_implicit,
            } => value_object(name, underlying, *from_implicit, *to_implicit),
            Type::Enum {
                underlying,
                flags,
                members,
            } => enumeration(name, underlying, *flags, members),
            Type::Custom { fields } => {
                check_fields(fields)?;
                custom(name, fields)
            }
        };
        files.insert(filename(name), format!("{PREFIX}{body}"));
    }
    for table in project.tables.values() {
        check_fields(&table.fields)?;
        files.insert(
            filename(&table.csharp_name),
            format!("{PREFIX}using MasterMemory;\n{}", row(project, table)?),
        );
    }
    Ok(files)
}
fn value_object(name: &str, underlying: &str, from: bool, to: bool) -> String {
    let mut code = format!(
        "namespace Masterdata.Generated\n{{\n    [global::MessagePack.MessagePackObject]\n    public readonly struct {name} : global::System.IEquatable<{name}>, global::System.IComparable<{name}>\n    {{\n        [global::MessagePack.Key(0)]\n        public {underlying} Value {{ get; }}\n        [global::MessagePack.SerializationConstructor]\n        public {name}({underlying} value)\n        {{\n"
    );
    if underlying == "string" {
        code.push_str("            if (value is null) throw new global::System.ArgumentNullException(nameof(value));\n");
    }
    code.push_str("            Value = value;\n        }\n");
    let equal = if underlying == "string" {
        "global::System.StringComparer.Ordinal.Equals(Value, other.Value)"
    } else {
        "Value.Equals(other.Value)"
    };
    let compare = if underlying == "string" {
        "global::System.StringComparer.Ordinal.Compare(Value, other.Value)"
    } else {
        "Value.CompareTo(other.Value)"
    };
    let hash = if underlying == "string" {
        "Value is null ? 0 : global::System.StringComparer.Ordinal.GetHashCode(Value)"
    } else {
        "Value.GetHashCode()"
    };
    let text = if underlying == "string" {
        "Value"
    } else {
        "Value.ToString(global::System.Globalization.CultureInfo.InvariantCulture)"
    };
    writeln!(code, "        public bool Equals({name} other) => {equal};\n        public override bool Equals(object? obj) => obj is {name} other && Equals(other);\n        public override int GetHashCode() => {hash};\n        public override string ToString() => {text};\n        public int CompareTo({name} other) => {compare};").unwrap();
    for (operator, expression) in [
        ("==", "left.Equals(right)"),
        ("!=", "!left.Equals(right)"),
        ("<", "left.CompareTo(right) < 0"),
        ("<=", "left.CompareTo(right) <= 0"),
        (">", "left.CompareTo(right) > 0"),
        (">=", "left.CompareTo(right) >= 0"),
    ] {
        writeln!(code, "        public static bool operator {operator}({name} left, {name} right) => {expression};").unwrap();
    }
    if from {
        writeln!(code, "        public static implicit operator {name}({underlying} value) => new {name}(value);").unwrap();
    }
    if to {
        writeln!(
            code,
            "        public static implicit operator {underlying}({name} value) => value.Value;"
        )
        .unwrap();
    }
    code.push_str("    }\n}\n");
    code
}
fn enumeration(name: &str, underlying: &str, flags: bool, members: &[(String, String)]) -> String {
    let mut code = "namespace Masterdata.Generated\n{\n".to_owned();
    if flags {
        code.push_str("    [global::System.Flags]\n");
    }
    writeln!(code, "    public enum {name} : {underlying}\n    {{").unwrap();
    let suffix = match underlying {
        "uint" => "U",
        "long" => "L",
        "ulong" => "UL",
        _ => "",
    };
    for (member, value) in members {
        writeln!(code, "        {member} = {value}{suffix},").unwrap();
    }
    code.push_str("    }\n}\n");
    code
}
fn custom(name: &str, fields: &[Field]) -> String {
    let mut code = format!(
        "namespace Masterdata.Generated\n{{\n    [global::MessagePack.MessagePackObject, global::MessagePack.MessagePackFormatter(typeof(global::Masterdata.Serialization.{name}Formatter))]\n    public readonly struct {name} : global::System.IEquatable<{name}>\n    {{\n"
    );
    for field in fields {
        writeln!(
            code,
            "        [global::MessagePack.Key({})]\n        public {} {} {{ get; }}",
            field.key,
            field_type(field),
            semantic::public_name(&field.name)
        )
        .unwrap();
    }
    let parameters = fields
        .iter()
        .map(|field| format!("{} {}", field_type(field), field.name))
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(code, "        public {name}({parameters})\n        {{").unwrap();
    for field in fields {
        if field.array {
            writeln!(code,"            if ({}.IsDefault) throw new global::System.ArgumentException(\"Array must be initialized\", nameof({}));",field.name,field.name).unwrap();
        } else if field.type_name == "string" && !field.nullable {
            writeln!(code,"            if ({} is null) throw new global::System.ArgumentNullException(nameof({}));",field.name,field.name).unwrap();
        }
        writeln!(
            code,
            "            {} = {};",
            semantic::public_name(&field.name),
            field.name
        )
        .unwrap();
    }
    code.push_str("        }\n");
    let equality = fields.iter().map(|field| {
        let property=semantic::public_name(&field.name);
        if field.array { format!("__ArrayEqual({property}, other.{property})") }
        else { format!("global::System.Collections.Generic.EqualityComparer<{}>.Default.Equals({property}, other.{property})",field_type(field)) }
    }).collect::<Vec<_>>().join(" && ");
    writeln!(code,"        public bool Equals({name} other) => {equality};\n        public override bool Equals(object? obj) => obj is {name} other && Equals(other);\n        public static bool operator ==({name} left, {name} right) => left.Equals(right);\n        public static bool operator !=({name} left, {name} right) => !left.Equals(right);\n        public override int GetHashCode()\n        {{\n            unchecked\n            {{\n                int hash = 17;").unwrap();
    for field in fields {
        let property = semantic::public_name(&field.name);
        if field.array {
            writeln!(
                code,
                "                hash = hash * 31 + __ArrayHash({property});"
            )
            .unwrap();
        } else if field.type_name == "string" {
            writeln!(code,"                hash = hash * 31 + ({property} is null ? 0 : global::System.StringComparer.Ordinal.GetHashCode({property}));").unwrap();
        } else {
            writeln!(code,"                hash = hash * 31 + global::System.Collections.Generic.EqualityComparer<{}>.Default.GetHashCode({property});",field_type(field)).unwrap();
        }
    }
    code.push_str("                return hash;\n            }\n        }\n");
    if fields.iter().any(|field| field.array) {
        code.push_str(include_str!("codegen/array.cs.txt"));
    }
    code.push_str("    }\n}\n");
    code.push_str(&custom_formatter(name, fields));
    code
}
fn custom_formatter(name: &str, fields: &[Field]) -> String {
    // MessagePack's integer-key constructor matching follows layout, whereas
    // SCHEMA-CUSTOM-017 fixes the public constructor in declaration order. A
    // native formatter calls that unchanged constructor with each explicit key.
    // Regression: independent_consumers_reload_nested_values_and_sparse_keys
    let mut code = format!(
        "namespace Masterdata.Serialization\n{{\n    public sealed class {name}Formatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Masterdata.Generated.{name}>\n    {{\n        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Masterdata.Generated.{name} value, global::MessagePack.MessagePackSerializerOptions options)\n        {{\n            writer.WriteArrayHeader({});\n            for (int key = 0; key < {}; key++)\n            {{\n                switch (key)\n                {{\n",
        fields.iter().map(|field| field.key).max().unwrap() + 1,
        fields.iter().map(|field| field.key).max().unwrap() + 1
    );
    for field in fields {
        writeln!(code,"                    case {}: global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<{}>(options.Resolver).Serialize(ref writer, value.{}, options); break;",field.key,field_type(field),semantic::public_name(&field.name)).unwrap();
    }
    code.push_str("                    default: writer.WriteNil(); break;\n                }\n            }\n        }\n");
    writeln!(code,"        public global::Masterdata.Generated.{name} Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)\n        {{\n            options.Security.DepthStep(ref reader);\n            try\n            {{\n                int length = reader.ReadArrayHeader();").unwrap();
    for (index, field) in fields.iter().enumerate() {
        writeln!(
            code,
            "                {} field{index} = default!;",
            field_type(field)
        )
        .unwrap();
    }
    code.push_str("                for (int key = 0; key < length; key++)\n                {\n                    switch (key)\n                    {\n");
    for (index, field) in fields.iter().enumerate() {
        writeln!(code,"                        case {}: field{index} = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<{}>(options.Resolver).Deserialize(ref reader, options); break;",field.key,field_type(field)).unwrap();
    }
    code.push_str("                        default: reader.Skip(); break;\n                    }\n                }\n");
    writeln!(code,"                return new global::Masterdata.Generated.{name}({});\n            }}\n            finally {{ reader.Depth--; }}\n        }}\n    }}\n}}",(0..fields.len()).map(|index|format!("field{index}")).collect::<Vec<_>>().join(", ")).unwrap();
    code
}
fn row(project: &Project, table: &Table) -> Result<String> {
    // MasterMemory 3.0.4 recognizes the documented short index-attribute syntax;
    // fully qualified PrimaryKey compiles as an attribute but is not collected
    // as a key by its generator. Keep symbol binding to the native dependency.
    // Regression: independent_consumers_reload_nested_values_and_sparse_keys
    let mut members = table
        .fields
        .iter()
        .map(|field| semantic::public_name(&field.name))
        .collect::<BTreeSet<_>>();
    members.insert(table.csharp_name.clone());
    for reference in &table.references {
        if !members.insert(reference.csharp_name.clone())
            || matches!(
                reference.csharp_name.as_str(),
                "Equals" | "GetHashCode" | "ToString" | "GetType"
            )
        {
            return Err(invalid(format!(
                "{}: Reference helper collision",
                reference.name
            )));
        }
    }
    let mut code = format!(
        "namespace Masterdata.Generated\n{{\n    [MemoryTable(\"{}\"), global::MessagePack.MessagePackObject]\n    public sealed partial class {}\n    {{\n",
        table.name, table.csharp_name
    );
    for field in &table.fields {
        writeln!(code, "        [global::MessagePack.Key({})]", field.key).unwrap();
        if let Some(order) = table
            .primary
            .fields
            .iter()
            .position(|name| name == &field.name)
        {
            writeln!(code, "        [PrimaryKey(keyOrder: {order})]").unwrap();
        }
        for (index, key) in table.secondary.iter().enumerate() {
            if let Some(order) = key.fields.iter().position(|name| name == &field.name) {
                writeln!(
                    code,
                    "        [SecondaryKey({index}, keyOrder: {order}){}]",
                    if key.non_unique { ", NonUnique" } else { "" }
                )
                .unwrap();
            }
        }
        writeln!(
            code,
            "        public {} {} {{ get; init; }}{}",
            field_type(field),
            semantic::public_name(&field.name),
            if field.type_name == "string" && !field.nullable && !field.array {
                " = null!;"
            } else {
                ""
            }
        )
        .unwrap();
    }
    for reference in &table.references {
        let resolved = project.resolve_reference(table, reference)?;
        let target = &project.tables[&reference.target_table];
        let return_type = if resolved.multi {
            format!(
                "global::MasterMemory.RangeView<{}>",
                base_type(&target.csharp_name)
            )
        } else {
            format!(
                "{}{}",
                base_type(&target.csharp_name),
                if resolved.optional { "?" } else { "" }
            )
        };
        writeln!(code,"        public {return_type} {}(global::Masterdata.Generated.MemoryDatabase database)\n        {{",reference.csharp_name).unwrap();
        code.push_str("            if (database is null) throw new global::System.ArgumentNullException(nameof(database));\n");
        if resolved.optional {
            let checks = reference
                .fields
                .iter()
                .map(|name| format!("{} is null", semantic::public_name(name)))
                .collect::<Vec<_>>();
            writeln!(
                code,
                "            if ({}) return {};",
                checks.join(" && "),
                if resolved.multi {
                    format!("{return_type}.Empty")
                } else {
                    "null".into()
                }
            )
            .unwrap();
            if checks.len() > 1 {
                writeln!(code,"            if ({}) throw new global::System.InvalidOperationException(\"Reference has partial null components\");",checks.join(" || ")).unwrap();
            }
        }
        let arguments = reference
            .fields
            .iter()
            .map(|name| {
                let field = table
                    .fields
                    .iter()
                    .find(|field| &field.name == name)
                    .unwrap();
                let property = semantic::public_name(name);
                if !resolved.optional {
                    property
                } else if field.type_name == "string" {
                    format!("{property}!")
                } else {
                    format!("{property}.Value")
                }
            })
            .collect::<Vec<_>>();
        let argument = if arguments.len() == 1 {
            arguments[0].clone()
        } else {
            format!("({})", arguments.join(", "))
        };
        writeln!(
            code,
            "            return database.{}Table.FindBy{}({argument});\n        }}",
            target.csharp_name,
            semantic::query_name(&reference.target_fields)
        )
        .unwrap();
    }
    code.push_str("    }\n}\n");
    Ok(code)
}

/// Native hydration is schema-specific lowering of validated values, not YAML
/// interpretation. Public generated artifacts contain no builder/input code.
pub fn builder(project: &Project) -> String {
    let mut code = include_str!("codegen/builder.cs.txt").to_owned();
    let mut body = String::new();
    for table in project.tables.values() {
        let name = &table.csharp_name;
        writeln!(body,"            var rows{name} = new global::System.Collections.Generic.List<{}>();\n            foreach (var input in document.RootElement.GetProperty(\"tables\").GetProperty(\"{}\").EnumerateArray())\n            {{\n                var fields = Map(input.GetProperty(\"values\"));\n                rows{name}.Add(new {}\n                {{",base_type(name),table.name,base_type(name)).unwrap();
        for field in &table.fields {
            writeln!(
                body,
                "                    {} = {},",
                semantic::public_name(&field.name),
                read_field(project, field, &format!("fields[\"{}\"]", field.name))
            )
            .unwrap();
        }
        writeln!(
            body,
            "                }});\n            }}\n            builder.Append(rows{name});"
        )
        .unwrap();
    }
    body.push_str("            var bytes = builder.Build();\n            var database = new global::Masterdata.Generated.MemoryDatabase(bytes);\n");
    for table in project.tables.values() {
        let name = &table.csharp_name;
        writeln!(body,"            if (database.{name}Table.Count != rows{name}.Count) throw new global::System.InvalidOperationException(\"Reload row count differs: {}\");\n            foreach (var expected in rows{name})\n            {{",table.name).unwrap();
        let arguments = table
            .primary
            .fields
            .iter()
            .map(|name| format!("expected.{}", semantic::public_name(name)))
            .collect::<Vec<_>>();
        let argument = if arguments.len() == 1 {
            arguments[0].clone()
        } else {
            format!("({})", arguments.join(", "))
        };
        writeln!(body,"                var actual = database.{name}Table.FindBy{}({argument});\n                if (!global::System.Linq.Enumerable.SequenceEqual(global::MessagePack.MessagePackSerializer.Serialize(expected), global::MessagePack.MessagePackSerializer.Serialize(actual)))\n                    throw new global::System.InvalidOperationException(\"Reload values differ: {}\");\n            }}",semantic::query_name(&table.primary.fields),table.name).unwrap();
    }
    body.push_str("            global::System.IO.File.WriteAllBytes(args[1], bytes);\n");
    code = code.replace("$BODY$", &body);
    let mut readers = String::new();
    for (name, declaration) in project.types.iter() {
        writeln!(
            readers,
            "        private static {} Read{name}(JsonElement input)\n        {{",
            base_type(name)
        )
        .unwrap();
        match declaration {
            Type::ValueObject { underlying, .. } => {
                writeln!(
                    readers,
                    "            return new {}({});",
                    base_type(name),
                    read_base(project, underlying, "input")
                )
                .unwrap();
            }
            Type::Enum { flags: false, .. } => {
                writeln!(readers,"            return global::System.Enum.Parse<{}>(input.GetProperty(\"value\").GetString()!, false);",base_type(name)).unwrap();
            }
            Type::Enum { flags: true, .. } => {
                writeln!(readers,"            {} value = 0;\n            foreach (var member in input.GetProperty(\"value\").EnumerateArray()) value |= global::System.Enum.Parse<{}>(member.GetString()!, false);\n            return value;",base_type(name),base_type(name)).unwrap();
            }
            Type::Custom { fields } => {
                readers.push_str("            var fields = Map(input.GetProperty(\"value\"));\n");
                writeln!(
                    readers,
                    "            return new {}({});",
                    base_type(name),
                    fields
                        .iter()
                        .map(|field| read_field(
                            project,
                            field,
                            &format!("fields[\"{}\"]", field.name)
                        ))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
                .unwrap();
            }
        }
        readers.push_str("        }\n");
    }
    code.replace("$READERS$", &readers)
}
fn read_base(project: &Project, name: &str, input: &str) -> String {
    if project.types.contains_key(name) {
        return format!("Read{name}({input})");
    }
    let value = format!("{input}.GetProperty(\"value\")");
    match name {
        "bool" => format!("{value}.GetBoolean()"),
        "string" => format!("{value}.GetString()!"),
        _ => format!(
            "{name}.Parse({value}.GetString()!, global::System.Globalization.CultureInfo.InvariantCulture)"
        ),
    }
}
fn read_field(project: &Project, field: &Field, input: &str) -> String {
    if field.array {
        return format!(
            "global::System.Collections.Immutable.ImmutableArray.ToImmutableArray(global::System.Linq.Enumerable.Select({input}.GetProperty(\"value\").EnumerateArray(), element => {}))",
            read_base(project, &field.type_name, "element")
        );
    }
    let value = read_base(project, &field.type_name, input);
    if field.nullable {
        format!("IsNull({input}) ? ({})null : {value}", field_type(field))
    } else {
        value
    }
}
